### ISSUE TITLE
Vite integration

### ISSUE THREAD

**Issue by machycek** [lingui/js-lingui#1016]
**Is your feature request related to a problem? Please describe.**
[Sveltekit](https://svelte.dev/blog/sveltekit-beta) has officially been released to public and I would love to use lingui with it. I see lot of people betting on Vite (Next has some plans as well) so it might be worth considering creating a plugin

**Comment by semoal** [comment]
We already have a little example with Linguijs + vite + react working. 
> https://github.com/capaj/vite-lingui-poc

Lingui.js is a library heavily built around `babel-plugin-macros`, this plugin allows to Lingui to compile strings on build time and be the lightest library out there and probably the fastest.

Vite setup with React works good because if you add the `reactRefresh` plugin adds babel under the hood, but i'm not sure how will work with Svelte (if it adds babel under the hood)

Once `esbuild` opens a bit more his AST API, I'm open to develop (If i can find some free time, really busy right now) a plugin for Lingui to work without babel, and use `esbuild` instead.

Meanwhile of course you can add the vite babel plugin and Lingui will work as expected.

We have two plugins (1x for Webpack, 1x for Snowpack) on Linguijs monorepo for hot-reload of the locale catalogs, probably a plugin for Vite could be created pretty easily. (Meanwhile we added a few weeks ago --watch mode in the cli, that listens for changes and auto-extract and auto-compiles)

**Comment by skovhus** [comment]
I created a working example without using the react refresh hack, by just using plain [vite-plugin-babel-macros](https://github.com/itsMapleLeaf/vite-plugin-babel-macros).

It seems pretty fast, but I’m curious to know how to improve it. 

https://github.com/skovhus/vite-lingui

**Comment by CamilleHbp** [comment]
I've manage to make it even easier than this.

The [@vitejs/plugin-react](https://www.npmjs.com/package/@vitejs/plugin-react) can have its babel configuration edited now.

Here is a sample of mine:
```js
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        // Use .babelrc files, necessary to use LinguiJS CLI
        babelrc: true,
        // Use babel.config.js files
        configFile: false,
      },
    }),
   ... your own plugin configuration here
]
```

I then added a `.babelrc` file with the following content:
```json
{
  "presets": [
    "@babel/preset-typescript",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic",
        "importSource": "react"
      }
    ]
  ],
  "plugins": ["macros"]
}
```
I had to change the `runtime` to automatic, otherwise the CLI tool was complainin with `importSource cannot be set when runtime is classic`. 
This is working for me, CLI is extracting and compiling fine, and I don't have errors anymore with Theme-UI.

I hope this helps!
