### ISSUE TITLE
Translating defaultProps with t()

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1037]
**Describe the bug**
When defaultProps are translated with t(), the translated value is never shown.

**To Reproduce**

For example, here is a simple component.

```

import React from 'react';
import { IonLoading } from '@ionic/react';
import { t } from '@lingui/macro';

interface MyProps {
  textToShow?: string,
}

const Loading: React.VFC<MyProps> = ({ textToShow }: MyProps) => (
  <IonLoading
    isOpen
    message={textToShow}
  />
);

Loading.defaultProps = {
  textToShow: t({ id: 'loading.text', message: 'Getting Ready...' }),
};

export default Loading;

```

Run `lingui extract`. Translate `loading.text` to something else, such as "Getting ready translated". Run `lingui compile`.  Change the app language and cause the loading component to trigger.  The text will be `Getting Ready...`, not `Getting ready translated`.

**Expected behavior**
defaultProps values should use the translation, not the original text.

- jsLingui version ``lingui --version`` 3.8.3
- Babel version ``npm list @babel/core`` @babel/core@7.12.3 
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
create-react-app via Ionic React v5

**Comment by semoal** [comment]
For dynamic translations it's recommended to use defineMessage mate. Give it a try

**Comment by ptmkenny** [comment]
Thanks!  Based on the [defineMessage docs](https://lingui.js.org/ref/macro.html#jsmacro-defineMessage), I tried this:

```
import React from 'react';
import { IonLoading } from '@ionic/react';
import { defineMessage } from '@lingui/macro';
import { i18n } from '@lingui/core';

interface MyProps {
  textToShow?: string,
}

const Loading: React.VFC<MyProps> = ({ textToShow }: MyProps) => (
  <IonLoading
    isOpen
    message={textToShow}
  />
);

const loadingText = defineMessage({
  id: 'loading.text',
  message: 'Getting Ready...',
});

Loading.defaultProps = {
  textToShow: i18n._(loadingText),
};

export default Loading;

```

But when I trigger the load component, I still see the original English `Getting Ready...`, and not the translation.

**Comment by semoal** [comment]
Let me try to reproduce it, if you can a codesandbox/stackblitz someting like that where i can debug it, would be really helpul

**Comment by ptmkenny** [comment]
Thanks.  I tried to set up a codesandbox but it keeps giving me strange errors.

I did manage to make a GitHub repo to reproduce the problem: https://github.com/ptmkenny/csb-ionic-lingui

`npm install`
`npm install -g @ionic/cli`
`ionic serve`

And then you will see "Default Title" at localhost:/8000 instead of "タイトル"-- even though the app is set to show Japanese only in [App.tsx](https://github.com/ptmkenny/csb-ionic-lingui/blob/main/src/App.tsx).

**Comment by semoal** [comment]
Sorry for the delay mate, I'm really busy right now with Rematch book and other projects and couldn't reproduce it since today.

![Screenshot 2021-04-12 at 12 01 43](https://user-images.githubusercontent.com/22656541/114377405-ea137a00-9b86-11eb-848b-1e59aa55f733.png)

I made it work, but I have to investigate the root cause looks like ionic is adding a i18n import somewhere and replaces the lingui i18n import

**Comment by semoal** [comment]
Alright, let me wrap some of my findings:

### `i18n._()` inside defaultProps doesn't re-render when changing locale.

This could be caused to how React re-renders it, I'm not an expert of how this is handled internally by React so not sure how can i help here, I'm open to any contribution that improves this experience.

Possible workaround:
```tsx
const MyPage: React.VFC<MyProps> = ({ title }: MyProps) => (
  <IonPage>
    <IonContent>
      {i18n._(title)}
...

const title = defineMessage({
  id: 'test.title',
  message: 'Default Title',
});

MyPage.defaultProps = {
  title,
};
```
With these changes correctly re-renders the component when the locale changes.

### `/* i18n */ ` commentaries are dangerous

We use them internally like #__PURE__# ones (for tree-shaking) to know which components are i18n components and should be extracted, this was the root cause of not being translated to japanase.

### About how to import locale datas

I've recommend to create a i18n.ts file and add there all the locales and import it in the root of your project, before @lingui/core import

```tsx
import { i18n } from '@lingui/core';
import { ja, en } from 'make-plural/plurals';
import { messages as messagesJa } from './locales/ja/messages';
import { messages as messagesEn } from './locales/en/messages';

i18n.loadLocaleData({
  ja: { plurals: ja },
  en: { plurals: en },
});
i18n.load({
  ja: messagesJa,
  en: messagesEn,
});
```

For a posterior activate in a useEffect hook:

```tsx

import './i18n';

import { i18n } from '@lingui/core';
import { I18nProvider } from '@lingui/react';

import AppRouter from './components/AppRouter';

const App: React.FC = () => {
  useEffect(() => {
    i18n.activate('ja');
  }, []);
  return (
    <IonApp>
      <I18nProvider i18n={i18n}>
        <AppRouter />
      </I18nProvider>
    </IonApp>
  );
};
```

### Change locale dynamically:

```tsx
 import { i18n } from '@lingui/core';
...

   <IonButton onClick={() => i18n.activate('en')}>
        English
      </IonButton>
      <IonButton onClick={() => i18n.activate('ja')}>
        Japanese
      </IonButton>
```
This code will work as expected and will re-render the screen with the corresponding translations.


I'm sorry that I couldn't help enough with the descriptor on defaultProps, but right now I'm not sure how can we fix this.

**Comment by ptmkenny** [comment]
Wow, thank you so much, this is very helpful.

This thorough response makes me very glad I chose lingui from among the many i18n js options. 😄

**Comment by ptmkenny** [comment]
Just an update to this: I've found a way to handle defaultProps which works better for me.  Sharing in case it helps anyone else:

```
const ButtonNext: React.VFC<MyProps> = ({ nextPage, linkText }: MyProps) => (
  <IonButton routerLink={nextPage} expand="full">
    { linkText === ''
      ? <Trans id="button.next_page">Next</Trans>
      : linkText}
  </IonButton>
);

ButtonNext.defaultProps = {
  linkText: '',
};
```

Doing it this way (set the default to null, and then use a conditional in the render to check for the default) correctly renders the default value, and I can also pass t() as a prop, which will be rendered correctly.

**Comment by sapandiwakar** [comment]
For anyone coming here searching to localize `defaultProps`, there is a small mistake in https://github.com/lingui/js-lingui/issues/1037#issuecomment-816633278. You should use `defineMessage` inside `defaultProps` (since this is an object that is evaluated only once) object and then translate the message inside the component like this: 

```js
import React from 'react';
import { IonLoading } from '@ionic/react';
import { defineMessage } from '@lingui/macro';
import { i18n } from '@lingui/core';

interface MyProps {
  textToShow?: string,
}

const Loading: React.VFC<MyProps> = ({ textToShow }: MyProps) => (
  <IonLoading
    isOpen
    message={typeof textToShow === 'string' ? textToShow : i18n._(textToShow)}
  />
);

Loading.defaultProps = {
  textToShow: defineMessage({
    id: 'loading.text',
    message: 'Getting Ready...',
  }),
};

export default Loading;
```
