### ISSUE TITLE
Support for svelte

### ISSUE THREAD

**Issue by JovanShandro** [lingui/js-lingui#1052]
Hi! I tried to use the plain javascript version on svelte but couldn't manage to make it work. Is there any plan to also add support for svelte in the future?

Thank you!

**Comment by semoal** [comment]
Currently I'm alone maintaining this project, but I'll be happy to add Svelte support to Lingui, but right now I'm out of free time. 

In a few weeks probably I'll could find some time to take a deeper look on this.

**Comment by ryanb** [comment]
Any update on this? I'd love to see svelte support as well. Anyone know of a work around in the meantime?

**Comment by ryanb** [comment]
@semoal did you ever have a chance to look into Svelte support? When running svelte through babel it seems to support the macro, however I'm not sure how to use `lingui extract` command with svelte files. Does it actually parse the JS? I suppose we could try one of these:
1. Extract the script tag from svelte
2. Run extract on the compiled svelte instead of the `.svelte` files. Not sure how this works with the macro though.

**Comment by thekip** [comment]
@ryanb you can check [Vue Extractor](https://github.com/lingui/js-lingui/blob/main/packages/extractor-vue/src/vue-extractor.ts) and do something similar for svelte using svelte compiler.

**Comment by ryanb** [comment]
@thekip thanks! Looks fairly simple.

**Comment by HenryLie** [comment]
For people looking to integrate Lingui into their Svelte projects, I also have the same need and created [svelte-i18n-lingui](https://www.npmjs.com/package/svelte-i18n-lingui). The syntax is very close to Lingui's macro syntax for JS but with some changes to add Svelte's reactivity on top. It also comes with an extractor to support its customized syntax.

Feel free to try it out and give your feedback!
