### ISSUE TITLE
Built PO file contains header with incorrect letter case

### ISSUE THREAD

**Issue by datafoo** [lingui/js-lingui#1071]
**Describe the bug**
Extracting PO file generates a file containing the header "Mime-Version: 1.0\n".

**Expected behavior**
Extracting PO file should generate a file containing the header "MIME-Version: 1.0\n" (note the difference in letter case).

**Additional context**

- jsLingui version ``lingui --version``: 3.9.0
- Babel version ``npm list @babel/core`` 7.14.3

"MIME-Version: 1.0\n" seems to be the correct case (http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html).

When opening a file generated by lingui with Poedit, a new header "MIME-Version: 1.0\n" is written in addition to the one already in the file ("Mime-Version: 1.0\n"). That creates unnecessary diff in git.

**Comment by nakkamarra** [comment]
If you grep this repo for `mime` it seems like a one line change just needs to happen in a few TS files and you can feel free to submit a quick and easy PR for that. However, it would be important to also update the example docs too, so that someone such as yourself wouldn't get confused when encountering contradictory information in the docs / repo / CLI output.
