### ISSUE TITLE
add support to pass custom i18n to "t" macro

### ISSUE THREAD

**Issue by seeden** [lingui/js-lingui#1090]
Hi.

I am using lingui on the server-side and everything works fine except macro "t"
It is using global i18n.
My react application is using custom i18n values.

I would like to use "t" as a hook (which will use my custom i18n value from I18nProvider)
```jsx
const t = useTrans();

t`My translation`;
```

My first idea was to create custom babel macro but I lose auto "extraction" of translations.

Can you add this hook or add support for passing i18n value to "t" function? Something like you used in version 2.x?

```jsx
t(i18n)`My translation`
```

or add support for i18n field
```jsx
t({
  i18n,
  message: `My translation ${variable}`,
})
```

When the user uses t as a function it will use custom i18n value instead of global value. 
Thank you for your hard work on this project.

I wanted to add this feature but I was lost in the source code :)

The third option can be to use defineMessage as template literal and I will use my own hook.
For example

```ts
const t = useTrans();

t(defineMessage`My ${variable}`);
```

Let me know what do you think about it. Maybe you have better solution

**Comment by tannerlyons** [comment]
This is also something I'm interested in. We are using lingui in a design system where we want the final distro to be very tree-shakable i.e. if a component isn't consumed, neither are its translations. We don't own the final build system so we cannot delegate this work to webpack in all cases.

We've figured out a way to do this but cannot use macros since we create our own version of i18n lazily. Because of this, we don't have a static way of referencing that i18n instance. 

We LOVE the extraction automation from lingui and we've resorted to using the [comment workaround here](https://github.com/lingui/js-lingui/issues/928#issuecomment-774694554) but it requires that extra comment to function properly.

It'd be great if we could pass that instance in at runtime vs build-time.

That could also alleviate the issues brought up here: https://github.com/lingui/js-lingui/issues/649
