### ISSUE TITLE
Use lingui.js with multiple packages

### ISSUE THREAD

**Issue by sitole** [lingui/js-lingui#1157]
Hey,
four our frontend we are using monrepository architecture.
We have split codebase per application and library (ui, utils..).

So, now we want to implement Lingui in our UI package. So we want prepare some React components separately with and then use this components in applications. It works well expect translations. We have installed Lingui in this packages and also works well. Its no problem to compile this library. Library is written in TypeScript and React.

But, after this i want use some component in application. If i paster `msgid` with translation directly into application `po` file also everything works good and component is translated. But after this i want to run `lingui extract` for example because i added some another translation to app. But `msgid` used in external component is not found and its marked as unused and commented.

I know Lingui searching components only in defined paths, but its possible to force Lingui to extract this translations from another package/node_modules folder etc?

## Out current configuration
```
{
  "fallbackLocales": {
    "default": "en"
  },
  "sourceLocale": "en",
  "format": "po",
  "locales": ["en", "cs", "es"],
  "catalogs": [
    {
        path: "src/locales/{locale}/messages",
        include: [
            "<rootDir>/src/**/*"
        ]
    }
  ],
}
```

**Comment by semoal** [comment]
This is something I want to explore for a long time, how Lingui works with monorepo of UI's and how can these translations co-exist together.
Will try to get some free time and create a repo where we can play and update Lingui to work nicely with monorepos.

**Comment by renchap** [comment]
I am having a similar issue: In a monorepo, I have both a web React app, a react-native mobile app, and a shared library with some common code.

I am not sure how to properly handle this, as:
- we have many common strings between the web & mobile apps, so it would be great to only translate them once
- we want to have some strings in the shared library translated
- we do not want to ship mobile-only string into our web-app, and the other way around. Strings in the shared library should be in both

Any ideas?

**Comment by Sitole** [comment]
Still actual?

**Comment by landsman** [comment]
I would love to see this in progress. Is it possible?

**Comment by semoal** [comment]
Ysss, I'll take care of this as soon as possible!

**Comment by thekip** [comment]
I will add a bit from my experience. The built-in Angular i18n tooling solve this problem effectively. 

Instead of globbing folders, they wrote a plugin for bundler (webpack). It is webpack's responsibility to discover and parse all files used in the current application. So while webpack is bundling your actual application, plugin extract the messages from a code. 

Instead of manually pointing extractor to places where msgs potentially might be such as: 

monorepo/shared-ui1/src
monorepo/shared-ui2/src
monorepo/shared-ui3/src

You point extractor to your entry points: 

monorepo/web-app1/src/main.ts
monorepo/mobile-app1/src/main.ts
monorepo/desktop-app1/src/main.ts

Then extractor automatically (thanks to webpack) follow all imports and discover all files needed for extraction. This effectively solved the issue even with packages which are installed from npm. 

The drawbacks of this are slower extraction process and more complicated setup. The plus of it, you can use your existing webpack setup with all yours aliases/path mappings setup.

After such extracting every app in monorepo would have it's own catalog of messages. The web app would not have messages from native and vice versa. Then localization platform will do the rest for you (reuse translation for the same keys)

**Comment by mgrosperrin** [comment]
Up

**Comment by mgrosperrin** [comment]
Why has this issue been closed? Nothing has been done yet and the latest status is that @semoal will work on it when he can.

**Comment by andrii-bodnar** [comment]
@thekip can this issue be resolved by the new experimental extractor feature?

**Comment by thekip** [comment]
Yes. Attach it to here https://github.com/lingui/js-lingui/issues/1458

**Comment by ThulinaWickramasinghe** [comment]
I have a main app which is written using Next.js and deployed as a [static export](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports). It also has custom npm packages, some of which are [transpiled on the go](https://nextjs.org/docs/app/api-reference/config/next-config-js/transpilePackages) and some of which come bundled.

I want to add Lingui to one of the packages which will be transpiled on the go. In the future, I plan to migrate to using Lingui in all the packages and the main app. I want translations in my packages to be versioned with the code in the packages. Also, I don't want my new package to have any dependencies with the main app, since there is a possibility that it will in the future be used in other apps as well. Is there any way that I can do this? 

I checked the experimental language extractor feature, but it didn't seem to me as a solution to this feature.
