### ISSUE TITLE
i18n.activate(language) takes time to activate language

### ISSUE THREAD

**Issue by divyansh7924** [lingui/js-lingui#1181]
**Describe the bug**
We are using the `@lingui/core` package in our backend to translate emails and push notifications.
We just found out that activating a language using `i18n.activate(_language)` takes some time to activate a language. We need to translate a term into different languages at once. Using `i18n.activate('zh-Hant-TW')` doesn't change the language to `zh-Hant-TW` instantly and we get the result in some other language that was activated before.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:
Catalogs are already loaded at this point

```
const translateString = (phrase, _language) => {
  i18n.activate(_language);
  return i18n._(phrase);
};

for (const lang of ['zh-Hant-TW', 'en', 'id', 'zh-Hans', 'ja']) {
    console.log(lang, translateString(t`*Invitation valid for limited period.`, lang));
  }
```

**Expected behavior**  

```
zh-Hant-TW *邀請有效期
en *Invitation valid for limited period.
id *Invitation valid for limited period.
zh-Hans *邀請有效期
ja ＊期間限定の招待です。
``` 
***Original Output***

```
zh-Hant-TW *邀請有效期
en *邀請有效期
id *Invitation valid for limited period.
zh-Hans *邀请有效期
ja *邀请有效期
``` 

**Additional context**

- jsLingui version `^3.10.2`
- Also tried on jsLingui version `^3.13.0`, same behaviour

**Comment by semoal** [comment]
Hey! Yes, this is a "known" issue since we use under the hood a class which extends an EventEmitter for doing the i18n like a singleton class where you can use it anywhere.

One thing I noticed on this line, is that probably we should use here: `this._locale` and `this._locales` instead of `this.locale` which is filled after eventemitter occurs. 
https://github.com/lingui/js-lingui/blob/main/packages/core/src/i18n.ts#L217

Could you try to replace it and give it a try? We'll love to release a such improvement in this area.

**Comment by divyansh7924** [comment]
Hey @semoal 
I tried it out, but the fix didn't work. Can you check if this is what you meant?
https://github.com/divyansh7924/js-lingui/commit/8cdbf20e7f733676c8376afd858bcbd415e41c4f

Thanks!

**Comment by thekip** [comment]
There no way to use one singletone on the backend with translation to diffrent languages. You will always recieve "unpredictable" results. Because on server side you have on VM for all of your request/users and if during processing one request this VM can handle few requests simlteaneously, so on the backend you should be extra-careful with "singletones" which data relay on user input (requested language it's also a user input) 

So your approach with custom i18n instance is a right thin. And there are no way to solve it differently. 
I would also add that if i had to do this task i would probably create i18n instance somehewere in the top middleware and assign it to the current request, and than in all other places will consume this instance from request: 

```ts
// pseudocode
const app = express();

app.use('*',  (req, res, next) => {
  // use headers / subpath / domain to determine locale or return defult if none is matched
  const locale = getLocaleFromRequest(req);
 
  req.i18n = initializeI18n(locale);
});

app.use('/index',  (req, res, next) => {
  res.send(t(req.i18n)`I'm alive`)
});
```
