### ISSUE TITLE
i18n.t fails on template literals

### ISSUE THREAD

**Issue by ludwigbacklund** [lingui/js-lingui#125]
Hi. I'm not sure if this is related to js-lingui or something else but I could use some help. I've been going through the tutorial and am now trying to translate a template literal with a variable that looks something like this:

``` i18n.t`Some text: ${someVar}` ```

but I get this error:

`Module build failed: TypeError: /.../file.js: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "MemberExpression"
    at Array.forEach (<anonymous>)`

Strings without any variable inside does not cause this error. Any help is appreciated, thanks!

**Comment by tricoder42** [comment]
Hello @ludwigbacklund,
this is definitely supposed to work! Just to clarify: is you example the same as in your code or do you use member expression instead of variable (e.g: ```i18n.t`Some text: ${object.key}` ```)?

Simple variables are supposed to work as seen in this [test case](https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-lingui-transform-js/test/fixtures/t/actual.js#L2). Support for expressions was added to JSX (see the [test case](https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-lingui-transform-react/test/fixtures/component-trans-expression/actual.js#L10)), but it seems that I forgot to add it to template literals as well.

**Comment by ludwigbacklund** [comment]
@tricoder42 Aha! Yes it is a member expression. So I should wait for an update on your side? :smile:

**Comment by tricoder42** [comment]
Yeah, I'm gonna fix it asap. This is inconsistency in API.

Just for your information, I generally prefer using variables in my code, because then I have named arguments in messages. Anything else is transformed to positional (numbered) argument:

```jsx
i18n.t`Hello {user.name}`
// extracted as: Hello {0}

const { name } = user
i18n.t`Hello {name}`
// extracted as: Hello {name}
```

**Comment by ludwigbacklund** [comment]
@tricoder42 Nice, thank you!

**Comment by tricoder42** [comment]
Fixed in latest versions of plugin, presets and related packages:
 - babel-plugin-lingui-extract-messages@1.1.9
 - babel-plugin-lingui-transform-js@1.0.5
 - babel-preset-lingui-js@1.0.6
 - babel-preset-lingui-react@1.0.12
 - lingui-cli@1.4.1
 - lingui-loader@0.1.1

**Comment by tricoder42** [comment]
Thank you for reporting this issue! 👍

**Comment by tricoder42** [comment]
The previous versions were unpublished from npm as mentioned in #127. Fixed in:

 - babel-plugin-lingui-extract-messages@1.1.10
 - babel-plugin-lingui-transform-js@1.0.6
 - babel-preset-lingui-js@1.0.7
 - babel-preset-lingui-react@1.0.13
 - lingui-cli@1.4.2
 - lingui-loader@0.1.2
