### ISSUE TITLE
Avoiding "Localisation function not found for locale"

### ISSUE THREAD

**Issue by MrOrz** [lingui/js-lingui#13]
`i18n.t` requires activated language to match one of the [CLDR language codes](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html). If not, `i18n.t` will fail within messageformat.js, with an error message that is not so informative: `"Localisation function not found for locale"`.

lingui can detect this when running the CLI`lingui add-locale`, and when `i18n.activate` is invoked.

**Comment by tricoder42** [comment]
Good point, thank you!

I would love to provide more meaningful help and give a hint what locales are valid, but it's a bit complicated. From the [http://cldr.unicode.org/index/cldr-spec/picking-the-right-language-code](docs):

1. Find ISO-639-3 language code
2. Use the two-letter code if there is one.
3. Verify that the code is in http://www.iana.org/assignments/language-subtag-registry
4. If the code occurs in http://unicode.org/repos/cldr/trunk/common/supplemental/supplementalMetadata.xml in the type attribute of a languageAlias element, then use the replacement instead.

😳 

Right now it just validates, that we have plurals for selected language (as messageformat.js does).

# Fixed in releases:
[lingui-i18n@0.2.2](https://github.com/lingui/js-lingui/releases/tag/lingui-i18n%40v0.2.2)
[lingui-react@0.3.1](https://github.com/lingui/js-lingui/releases/tag/lingui-react%40v0.3.1)
[lingui-cli@0.2.1](https://github.com/lingui/js-lingui/releases/tag/lingui-cli%40v0.2.1)
