### ISSUE TITLE
User language and system language rules

### ISSUE THREAD

**Issue by Eishpirate** [lingui/js-lingui#133]
Not sure if this is already possible, but we have a requirement that a User can select the language they'd like to see the application in, but then there would be certain fields that wouldn't be affected by the user language, but rather the language of the Company they're logged into.

For example, a User could be using the application for a US based company and need to report on Sales Tax, but they wanted the language to be displayed in French. In France they don't use the term "Sales tax" but rather "VAT". 

So we'd need to display all text in French except fields with "Sales  tax". 

We could choose not to wrap the "Sales tax" component in js-lingui but then we'd have to internationalize that component, based on the base language of the company.

The only way I can see this working, is if we have two instances of js-lingui. One for User's language text and one for Companies.

Is this the most eloquent solution?

**Comment by tricoder42** [comment]
Hello @Eishpirate,
that's very interesting usecase.

It really sounds like you need two instances of i18n. It's easy to do it with vanilla JS – there's `setupI18n` factory function in `lingui-i18n` package. However, it's not supported right now with `lingui-react` because i18n object is passed through context. Even when you create two instances of this object, they would overwrite each other.

So question is: How many translation you need to handle in the second language? Would it be convenient for you to use React components for use language and custom `i18n` object for company language? This could work only in a case when you don't have to translate many things in company's language...

Otherwise we could add one or two props to `withI18n` and `I18nProvider` so we can control the name of context property which is used to pass i18n object. Not big deal I guess.

**Comment by Eishpirate** [comment]
Hey @tricoder42, sorry for late reply. Christmas and New Years is a mad house :) We have put this issue on hold for now, but when we get back to it in the next month or so, we're going to use your suggestion to use React components for user language and custom i18n object for company language. Will update you with the results when we've implemented. 

Thanks for your help :)

**Comment by tricoder42** [comment]
Ok, no worries. Feel free to reopen if you have more question!
