### ISSUE TITLE
Inconsistency between macro docs and typings/code

### ISSUE THREAD

**Issue by thekip** [lingui/js-lingui#1433]
While working on https://github.com/lingui/js-lingui/pull/1340 found few more things: 

1. Docs states there should be a prop `format` https://lingui.dev/ref/macro#plural-1 in `<Plural>` and `<SelectOrdinal>` but there no such prop in macro typings. And also i don't see that prop in the [`Trans` component](https://github.com/lingui/js-lingui/blob/main/packages/react/src/Trans.tsx#L14-L24). Need to validate this and or delete it from docs, or fix it in the code.  
2. There are also more props for <Trans> than written in the docs. 
   ```ts
    type TransProps = {
      id?: string
      comment?: string
      context?: string
      render?: (props: TransRenderProps) => ReactElement<any, any> | null
      i18n?: I18n
    }
   ```
   Need to check, do we really need all that props on the macro (`render`? ) and update code and docs.

**Comment by tricoder42** [comment]
1. The `format` prop allows you to customize formatting of number passed to plural/selectOrdinal. It's used here https://github.com/lingui/js-lingui/blob/main/packages/core/src/context.ts#L22. `Trans` component doesn't need it because it doesn't formats any values.
2. Some props on macro were simply passed down to the actual function/component. I believe macro props were always subset of function/component props.
