### ISSUE TITLE
Production env some text render id as unexpected

### ISSUE THREAD

**Issue by yunsii** [lingui/js-lingui#1612]
**Describe the bug**
When I set NODE_ENV to "test", it work well after build. After deploy in production env, some text render id as unexpected.

**To Reproduce**
```tsx
// @lingui/core
// [warning] Non production env will compileMessage
if (process.env.NODE_ENV !== "production") {
  translation = isString(translation) ? compileMessage(translation) : translation;
}

// My code
// provider
export default function I18n({
  translation,
  children,
}: {
  translation?: any
  children: React.ReactNode
}) {
  const textLocale = useTextLocale()
  useState(() => {
    i18n.loadAndActivate(textLocale, translation || {})
  })

  useEffect(() => {
    i18n.loadAndActivate(textLocale, translation || {})
  }, [textLocale, translation])

  return <I18nProvider i18n={i18n}>{children}</I18nProvider>
}

// page
const test = t`world`
export const Page = () => {
	return (
		<div>
			<Trans>hello</Trans>
			{test}
		</div>
	)
}
```
In production env, t`world` will render id instead.

**Expected behavior**
- keep same render result after build with production, staging, test?
- check call i18n._ function before load and activate?

**About**
- jsLingui version `4.0.0-next.7`
- Babel version `no need in v4?`
- Macro support:
  - [x] I'm using SWC with `@lingui/swc-plugin`
  - [ ] I'm using Babel with `babel-macro-plugin`
  - [ ] I'm not using macro

**Comment by thekip** [comment]
```
t`world`
```
this call returns a string.  It wouldn't reflect to changes outside of React's functions (or any other re-executed context_, because this code is executed once when module is initialized. This is just javascript. 

Use this:  https://js-lingui-git-next-lingui.vercel.app/tutorials/react-patterns#lazy-translations

And setup an[ eslint rule ](https://www.npmjs.com/package/eslint-plugin-string-to-lingui?activeTab=readme#:~:text=/%3E%3B-,t%2Dcall%2Din%2Dfunction,-Check%20that%C2%A0)to prevent this kind of errors in future.
