### ISSUE TITLE
react native expo i18n.date and i18n.number return some string but not formatted date

### ISSUE THREAD

**Issue by dimonnwc3** [lingui/js-lingui#1706]
**Describe the bug**
react native expo i18n.date and i18n.number return some string but not formatted date

**To Reproduce**
```tsx
import { i18n } from "@lingui/core"
import { messages as enMessages } from "../locales/en/messages"

i18n.loadAndActivate({
  locale: "en",
  messages: {
    en: enMessages,
  },
})

console.log(i18n.date(new Date())) // 0,date
console.log(i18n.number(10)) // 0,number
new Intl.DateTimeFormat().format(new Date()) // works as expected
```

**Expected behavior**
should return formatted date and number

**Additional context**
seems it returns function name and arguments count?

`Intl.DateTimeFormat` works as expected

- jsLingui version ``4.2.1``
- Babel version ``7.22.5``
- RN version ``0.71.8``
- Expo version ``48.0.15``
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
```
module.exports = function (api) {
  api.cache(true)
  return {
    presets: ["babel-preset-expo", "@lingui/babel-preset-react"],
    plugins: ["macros"],
  }
}
```

**Comment by thekip** [comment]
Actually, i have no idea. If you can debug and find a root cause, it would be awesome. or @vonovak may be you can help?

**Comment by vonovak** [comment]
I just checked the RN example in https://github.com/lingui/js-lingui/tree/main/examples/react-native

And it works fine for me:

<details>
  <summary>screenshot</summary>
  
![Simulator Screenshot - iPhone 14 Pro - 2023-06-22 at 00 09 17](https://github.com/lingui/js-lingui/assets/1566403/27a0050d-2666-4e7a-bb51-100623c428e1)

</details>


`console.log(i18n.date(new Date()))` works fine also.

@dimonnwc3 if you can reproduce the issue in the example app, please point us to the diff. Otherwise I don't think this is actionable.

Thank you :)

**Comment by dimonnwc3** [comment]
thanks I found an issue:

I was calling loadAndActivate with wrong arguments, passing messages for all locales instead of single
```
i18n.loadAndActivate({
  locale,
  locales: [currentLocale.languageTag],
  messages: {
    en: enMessages,
    de: deMessages,
  },
})
```


here is the fix
```
i18n.load({
  en: enMessages,
  de: deMessages,
})

i18n.activate(locale, [currentLocale.languageTag])
```
