### ISSUE TITLE
RSpack Lingui Example

### ISSUE THREAD

**Issue by Collinbrown95** [lingui/js-lingui#1749]
I have a use case where Lingui-JS is used for i18n in combination with [RSpack](https://www.rspack.dev/) as a web bundler.

I recently worked through the [Lingui React Example](https://lingui.dev/tutorials/react) with some small adaptations so that RSpack was used as a bundler instead of webpack (see my [rspack-lingui](https://github.com/Collinbrown95/rspack-lingui) repo for the reference implementation).

Given that someone else might have a similar use cases, it might be helpful to have an rspack-lingui example in the [examples](https://github.com/lingui/js-lingui/tree/main/examples) folder of this repository.

Would you be interested in a PR to add the example described above to the examples folder?

**Comment by thekip** [comment]
Yes, we would be interested. 

I started to write that we can use SWC plugin with built-in SWC loader, and keep RSpack as fast as possible without using babel, but [than found ](https://www.rspack.dev/guide/loader.html#builtinswc-loader)

> Loader's [configuration](https://swc.rs/docs/configuration/compilation) is aligned with the JS version of swc-loader (**SWC plugins will be provided in future releases and are currently not supported)**.

😢

Anyway, i would add this to the readme of example just to avoid another people to dig into documentation to understand why you need to use babel instead of built-in loader. 

BTW you can use babel only for macro transformation, and left all other transformations for faster built-in swc loader. I'm not sure how much faster it would be, but it seems the better approach than completely override it with babel.
