### ISSUE TITLE
Extract is not working with pnpm workspace with hoist disabled

### ISSUE THREAD

**Issue by MPeloquin** [lingui/js-lingui#1801]
**Describe the bug**
Using `pnpm` [workspaces](https://pnpm.io/workspaces) and [hoist](https://pnpm.io/npmrc#hoist) disabled, `lingui extract` on v4 breaks with `Cannot find module '@lingui/macro'`

**To Reproduce**
Have a pnpm workspace
Disable hoist in `.npmrc`
Have a lingui v4 project
Run `extract`

See repro: https://github.com/MPeloquin/LinguiV4Extractpnpmissue

**Expected behavior**
Should be able to run extract without enabling hoist

A workaround is to add `hoist-pattern[]=*@lingui/macro*` in `.npmrc`

**Additional context**
pnpm version: 8.7.4

- jsLingui version ``lingui --version`` 4.5.5
- Babel version ``npm list @babel/core`` 7.23.3
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite) Vite

**Comment by thekip** [comment]
Well, it seems there is nothing I can do about it. `@lingui/cli` doesn't directly depend on `@lingui/macro`, instead it depends on `babel-plugin-macros`. 
The `babel-plugin-macros` is designed to actually implicitly depends (require) on "macros" packages discovered in your source code, but obviously doesn't state this packages in its own `package.json`, so your package manager doesn't know how to handle them correctly. 

I think your solution is ok for this macro, and any other you might use in your code. 

For the future plans, i have been thinking for long time that it's better to switch from `babel-plugin-macros` to just simple babel plugin. Because `babel-plugin-macros` just becoming more and more "out" from modern ecosystem.
