### ISSUE TITLE
Dynamic loading not working with Expo

### ISSUE THREAD

**Issue by 2ico** [lingui/js-lingui#1838]
**Describe the bug**
Dynamic loading with expo@49.0.21 does not work.

``` LOG  I18nProvider rendered `null`. A call to `i18n.activate` needs to happen in order for translations to be activated and for the I18nProvider to render.This is not an error but an informational message logged only in development.```

It does work using loadAndActivate.

**To Reproduce**

```tsx
import { i18n } from "@lingui/core"
export const defaultLocale = "en";
export async function dynamicActivate() {
    const { messages } = await import(`/locales/en/messages`);
    i18n.load(locale, locales[locale].messages);
    i18n.activate(locale);
 }
```

```
import { I18nProvider } from '@lingui/react';
import { i18n } from '@lingui/core';
import { defaultLocale, dynamicActivate } from "@/lib/i18n";

export default function RootLayout() {

  useEffect(() => {
    // With this method we dynamically load the catalogs
    dynamicActivate("fr");
  }, []);

// etc.

}
```

**Expected behavior**
I expect to be able to load translations at runtime.

**Additional context**

- jsLingui version 10.2.5
- Babel version 7.23.6
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [X] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Using Expo 49

**Comment by thekip** [comment]
This message says that your app is trying to render before your catalogs is loaded. Loading catalog is async operation, and you should block react rendering somehow until catalogs are loaded. Or load catalogs before rendering react app (say outside of react).

Since loading catalogs is in userland, and could be done in many ways is up to you how you will load and await it.
