### ISSUE TITLE
Missing auto-generated `id` for `<Trans>` macro

### ISSUE THREAD

**Issue by simlmx** [lingui/js-lingui#1856]
**Describe the bug**
When I pass my code through babel, `` t`Hello World` `` macros correctly get an automatic `id`, but not `<Trans>Hello World</Trans>`.

**To Reproduce**

A full reproduction is available here:
https://github.com/simlmx/repro-lingui-missing-id/tree/main

If you look at the `dist/index.js` file, you'll see than the ``t`Hello World`` part correctly has an auto-generated id:
```js
i18n._(
  /*i18n*/
  {
    id: "OVvBzN",
    message: "Hi World"
  }
)
```

However, the `<Trans>` part becomes

```js
jsx(Trans, {
    children: "Hello World"
})
```
without an `id`.

**Expected behavior**
The output code should contain auto-generated ids for `<Trans>`.

**Additional context**

Everything can be found in the reproduction repo.

```
>: npx lingui --version
4.7.1

>: npm list @babel/core
repro-lingui-missing-id@1.0.0 /Users/simon/code/repro-lingui-missing-id
├─┬ @babel/core@7.23.9
│ └─┬ @babel/helper-module-transforms@7.23.3
│   └── @babel/core@7.23.9 deduped
├─┬ @lingui/cli@4.7.1
│ └── @babel/core@7.23.9 deduped
└─┬ @rollup/plugin-babel@6.0.4
  └── @babel/core@7.23.9 deduped

>: cat .babelrc
{
  "plugins": ["macros"]
}
```

- [x] I'm using Babel with `babel-plugin-macros`

I'm using a setup with Typescript and Rollup.

**Comment by thekip** [comment]
It's because you have typescript plugin before babel plugin. The lingui macro is looking for `Trans` JSX nodes in the AST, however after typescript plugin they are already transpiled to js and could not be matched and picked up by macro. 

There are few possible solutiuons:

- drop typescript and use only babel (for typescript transpiling as well)
- If dropping typescript is not possible (for example because of using legacy decorators + emitDecoratorMetdata?) you can set `"jsx": "preserve",` in `tsconfig.json` so JSX statements would be passed as-is to the babel.
- Consider moving to SWC which is not only faster, but also supports `emitDecoratorMetdata` and could be used as drop-in replacement for tsc

**Comment by simlmx** [comment]
Thanks for the quick reply!

I see this makes sense. Indeed using `"jsx": "preserve"` and adding the `@babel/preset-react"` preset made it work.

Should there be anything in the doc about this? There is a [Typescript section][1] but it reads:
> You should not need to do anything to get type support working.


[1]: https://lingui.dev/guides/typescript

**Comment by thekip** [comment]
> You should not need to do anything to get type support working.

**type support**

For macro support docs says that you need either babel or SWC compiler. And this is quite unusual to have typescript and babel together in 2024, since babel can transpile the typescript code since long ago, and typescript could be used separately only to check types (not for transpiling)

**Comment by simlmx** [comment]
Here is where I was coming from, in case it makes the use-case clearer.

My starting point was a pure Typescript project (no Babel or SWC whatsoever). What I'm doing is closer to a react component library than to a website, and I'm happy without any transpilation. I then simply followed the [React project][1] instructions to install `lingui`.


Thanks again for the help!

[1]: https://lingui.dev/tutorials/setup-react
