### ISSUE TITLE
Cannot find type definition file for './node_modules/@lingui/macro/global'.

### ISSUE THREAD

**Issue by welsea** [lingui/js-lingui#1869]
**Describe the bug**
`tsconfig.json` reports an error after adding lingui in types.

**To Reproduce**
Follow the documentation, 
1. install packages by using:
  ```bash
  npm install --save-dev @lingui/cli @lingui/macro babel-plugin-macros @babel/core
  npm install --save @lingui/core
  ```
2.  In `tsconfig,json`
```js
{
  "compilerOptions": {
    "types": ["./node_modules/@lingui/macro/global"]
  }
}

```

**Expected behavior**
`tsconfig.json` does not report any error.

**Additional context**
```json
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@lingui/cli": "^4.7.1",
    "@lingui/macro": "^4.7.1",
    "babel-plugin-macros": "^3.1.0",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@lingui/core": "^4.7.1",
  }
```
under `./node_modules/@lingui/marco` there is no `global`

**Comment by andrii-bodnar** [comment]
@welsea thanks for pointing this out!

The [TypeScript](https://lingui.dev/guides/typescript) documentation looks a bit misleading because the `global.d.ts` file is not being included in the distribution after the migration to `unbuild` (https://github.com/lingui/js-lingui/releases/tag/v4.0.0-next.4)

@thekip do we just need to include it in the `files` array in the `package.json`?

**Comment by thekip** [comment]
I wouldn't want to do that. it's been a while since 4.0 release and it doesn't seem to be used much. This solution with "global.d.ts" file was highly questionable initially i don't want to continue supporting this.
I would instead remove this from the documentation and focus on [separating the macro](https://github.com/lingui/js-lingui/issues/1361) into a js and react version
