### ISSUE TITLE
Support backup messages

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1886]
**Is your feature request related to a problem? Please describe.**

The problem is that on message updates, lingui will erase the previous translation since the source message changed, which is expected, but in reality, a lot of times, the old translation might be better than the english fallback, so it would be nice to support a way to mark the message is compatible with previous translation so we can keep using the old translation in the meantime.

**Describe proposed solution**

```
<Trans backupMessage="Today is a good day!">Today is a great day!</Trans>
```

then in generated message catalog:
```
#. js-lingui-id: aaaa
msgid "Today is a good day!"
msgstr "¡Hoy es un buen día!"

#. js-lingui-id: ddd
msgid "Today is a great day!"
msgstr ""
```

and in the compiled es message catalog:

```
{
  "aaa": "¡Hoy es un buen día!",
  "ddd": "¡Hoy es un buen día!"
}
```

before the final translation is back

**Comment by aseerkt** [comment]
Maybe using [context](https://lingui.dev/tutorials/explicit-vs-generated-ids#context) the right choice here.
What is `aaa` and `ddd` in your example?
@taozhou-glean

**Comment by taozhou-glean** [comment]
the `aaa` | `ddd` is the generated lingui id, its some sha of the message + context

this is different with context use case, but to make the translation more resilient to small changes, like in above example, when you change `good` -> `great`, in most of languages, we prefer to keep the original translation (`good`) over english fallback

**Comment by thekip** [comment]
I'm not interested in this change. What you want could be achieved using a good TMS with Translation Memory

**Comment by taozhou-glean** [comment]
I want to re-open this since this has come up a few more times for us, a lot of time, the change can be significant enough that Translation Memory will not be helpful (a low match ratio threshold here can lead to unexpected matches that we don't want here)

like `<Trans backupMessage="Export">Click to export your data</Trans>` - we still want to show `Export` before we have the new message `Click to export your data` translated

**Comment by thekip** [comment]
I think you probably need an explicit id, or use default language as explicit ids.

Say you have en-GB as your default language. You write all messages in the sourcecode in that language. Instead of showing this language to the users directly, you can rename it to some non-exisiting language, (eq `default`), and use a translation file for en-GB. 

This would be a compromise between still having all lingui macro goodies and flexibility of explicit ids. 

So in your case you will have in the source code: 

```jsx
// sourceLocale = "default"
<Trans>Export</Trans>
```

`default.po` has msgid `Export`
`en-GB.po` has msgid `Export` msgstr `Click to export your data`
`pl-Pl.po` has msgid `Export` and it's own translation

So instead of changing the en-GB message in the source code and wiping all translation, you change the translation file and source file still kept the same.

**Comment by taozhou-glean** [comment]
hmm that will require manual changes on the po files right ? I was hoping something more transparent to engineers, so they don't even need to know about the message catalog file, all things related to i18n they need to perform is the `marking` phase (so mark the string with lingui macro to extract, and mark it with the right message to fallback)

**Comment by thekip** [comment]
> hmm that will require manual changes on the po files right ?

No it doesn't. Everything stay the same, developers will not touch po files manually. They write your "fallback" messages as source message and magic happened in translation phase.
