### ISSUE TITLE
Migrate to the latest version of Lerna

### ISSUE THREAD

**Issue by andrii-bodnar** [lingui/js-lingui#1970]
Currently, we are using Lerna 6.5.

There have been a couple of major releases, as well as a lot of minors and patches.

- [7.0.0](https://github.com/lerna/lerna/releases/tag/7.0.0)
- [8.0.0](https://github.com/lerna/lerna/releases/tag/v8.0.0)
- [Changelog](https://github.com/lerna/lerna/blob/main/CHANGELOG.md)

It would be great to upgrade to the latest version.

The v8 dropped Node 16 support, so we should do this migration within Lingui v5.

**Comment by timofei-iatsenko** [comment]
What flows in this repo Lerna covering? I think we can use more modern tool for that, such as changeset. Also we can use built-in package manager's features for bumping dependencies of related packages from monorepo (`workspace:*`)

**Comment by andrii-bodnar** [comment]
It's responsible for:

- Automatic version bump (including related dependencies) which is based on commits made since the previous release.
- Changelog generation for all the packages.
- Creating git tag + release + release notes generation.
- Publishing of the `latest` or `next` version for all the packages to NPM.

Examples:

- [Version + changelogs](https://github.com/lingui/js-lingui/commit/263faa5b8cbe07ea1bbe4f5902794f29b773984d#diff-2d72bdead8afa0798d18995311992d684348a694c2d5e214e8e4d2b6153e4821R2)
- Release commands: https://github.com/lingui/js-lingui/blob/d0e45bcd2f641c19a91070d2e3f31a2c21f0009c/package.json#L29-L30

There are no problems with this tool in our use case, it works pretty well.

**Comment by timofei-iatsenko** [comment]
There are few benefits of newer tools:

- With a changeset, it's easier to create individual changelogs for packages. Existing changelogs are useless. 
- Using `workspace:` protocol in the package.json helps to avoid merge conflicts, and also situations when you have a parallel branch which has references to the specific monorepo versions, and this versions was not bumped by lerna because it wasn't in the `main` on the moment of release. 

The rest i think is pretty the same and perfectly serve the purpose. My intention to move out from lerna because, even, NX took a stewardship on that package there not much development at the moment and i would consider this package rather legacy.
