### ISSUE TITLE
Trans from @lingui/react shall fallback to its message if there is no translation

### ISSUE THREAD

**Issue by anbotz** [lingui/js-lingui#2022]
i'm using a mix of `Trans` from macro and from react in my app
`Trans` from macro for everything, except for the dictionnaries

```
import { msg } from '@lingui/macro'

export const DICTIONNARY_TRANSLATE = {
  foo: msg`bar`,
}
```

```
import { Trans } from '@lingui/macro'

<Trans id={DICTIONNARY_TRANSLATE['foo'].id} />
```

i'm quite lazy : i don't translate my native langage and keep the msgStr to "" in its .po file
With `Trans from macro`, it is not a problem, if there is no translate, lingui keeps the string between tags
With `Trans from react`, if there is no translate, lingui keeps the id instead

Do i miss something, or would it be better to show the string here `msg`<string>`` instead ?

**Comment by thekip** [comment]
> i'm quite lazy : i don't translate my native langage and keep the msgStr to "" in its .po file

Set `sourceLocale`  in lingui.config to your native language and it will `msgstr` automatically for you.

> With Trans from macro, it is not a problem, if there is no translate, lingui keeps the string between tags
> With Trans from react, if there is no translate, lingui keeps the id instead

It's wrong, you probably tried only in Dev mode, not in production. There is nothing to fallback, because macro is stripping a default message in production builds to save bytes. The fallback to default message happend during compilation of catalogs. 

To see fallbacks in react Trans in development you can: 

```jsx
import { Trans } from "@lingui/react";

<Trans {...DICTIONNARY_TRANSLATE['foo']} />
```

**Comment by anbotz** [comment]
i'm sorry, i created this issue before checking my extraction ... i forgot to extract some translates :( 

at least I discovered `sourceLocale` ! :sweat_smile: 

thanks and sorry again
