### ISSUE TITLE
`defineConfig` uses `node:fs` and breaks with Next.js middleware. `LinguiConfig` is not exposed for TypeScript support.

### ISSUE THREAD

**Issue by cedeber** [lingui/js-lingui#2135]
**Describe the bug**
`defineConfig` seems to rely on `"node:fs"`, which breaks Next.js middleware usage. Next.js reports that Node.js APIs can't be used in edge functions.

Additionally, `LinguiConfig` is not exposed for use with TypeScript. This means we can't benefit from `defineConfig` when working with Next.js, and instead, we're left relying on JSDoc.

Is having `defineConfig` just for the sake of having it truly necessary?

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

In `middleware.ts` I import it to have access to the same locales array.
```tsx
import linguiConfig from "./lingui.config";
const { locales } = linguiConfig;
```

**Expected behavior**
Usage of `satisfies LinguiConfig` with `export defaut config` seems to be ok to me.

**Comment by timofei-iatsenko** [comment]
Well, there is a bunch of problems leading to this issue

Firstly, `defineConfig` doesn't use anything from `node:fs`.  `defineConfig` is defined in the "@lingui/conf" together with `LinguiConfig` (so you can use it directly), but for simplicity it re-exported from "@lingui/cli"

Because "@lingui/cli" is built as a CJS only package, this re-export transpiles down to something like 

```js
var conf_1 = require("@lingui/conf");
Object.defineProperty(exports, "defineConfig", { enumerable: true, get: function () { return conf_1.defineConfig; } });
```

Which is literally importing everything from "@lingui/conf" where something is using "fs". Unfortunately, it is not easy to change. 

So workaround for you - install "@lingui/conf" and use `defineConfig` or `LinguiConfig` directly.

**Comment by cedeber** [comment]
Ok, thanks for the explanation. Looks like `fs` is still uses for the `configExists` function. But the `LinguiConfig` is indeed exposed from there.
