### ISSUE TITLE
Predictable message catalog output when using lingui extract

### ISSUE THREAD

**Issue by queicherius** [lingui/js-lingui#229]
I would love if `lingui extract` output the JSON file in a predictable way (e.g. ordered alphabetically), since we check in the resulting translation file and the shuffling of keys due to source code changing positions generates a lot of noise in the diffs.

I'm up to create a PR for this if you'd like.

**Comment by nicolas-cherel** [comment]
Yes, I was bothered by that too. I'm not sure that an alphabetical order on key is the best choice though, since order would change with keys change.
I'd suggest an order on first origin:line with origins sorted alphabetically.

**Comment by tricoder42** [comment]
Hey @queicherius, this is reasonable request. I'm wondering what would be the best sort.

- by message ID
- by first origin and message ID
- by first origin and line

I guess all of them have pros and cons and all of them are better than random sort. I still think sorting messages alphabetically by message ID is the best choice, because changed message ID is usually different message. What do you think, @nicolas-cherel?

**Comment by queicherius** [comment]
Personally, I would prefer message ID.

When using origin the messages will move around when components get moved around or messages get re-used somewhere else (working with React, in our fairly large codebase that happens quite regularly).

When using message ID they (should) only move around when the message changed.

**Comment by nicolas-cherel** [comment]
Yes sure, it's a tradeoff between the twos, so I'll just expose my rationale: 

I like the message position in code because a react refactor that causes components moving around either it should not change messages, so changeset is a not brainer (those messages just moves), or for a big refactor, changed messages are likely that have their context change, so semantically in the app they are different, and can't be treated as rewording.

If you order on message Id a rewording might move a message or not, making difficult to see in the diff that it's just a rewording.

That said, order by Id also has the convenient property that it'll be directly searchable in the `messages.json` file 😋, plus people that handcraft ids for each message might not find any value in having them sorted by position inside codebase.

**Comment by tricoder42** [comment]
Thank you @queicherius and @nicolas-cherel for your inputs!

Let's sort it alphabetically for now. We might make it configurable in the future, but I like the simplicity of alphabetic sort.

@queicherius, still interested in PR?

**Comment by tricoder42** [comment]
Fixed and released in [v2.2.0](https://github.com/lingui/js-lingui/blob/stable-2.x/CHANGELOG.md#220-2018-07-04). Thanks to all involved!
