### ISSUE TITLE
CLI babel-core error

### ISSUE THREAD

**Issue by queicherius** [lingui/js-lingui#238]
I have a small issue with using the CLI tool. My project uses `@babel/core@^7.0.0-beta.49` and `@lingui/cli@^2.0.7`. Running the CLI tool now throws the following error:

> Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

If I now go and delete `node_modules/@lingui/cli/node_modules/babel-core/`, everything works as expected.

**Comment by tricoder42** [comment]
Yeah, this seems like a bug caused mismatched Babel versions. jsLingui uses Babel 6 and it's not possible to use both versions of Babel in the same project. There we're several issues when jsLingui started using Babel 7 and I had to revert back because it's breaking change.

I'm hoping to release jsLingui 3.x, which would run on Babel 7 and publish both versions in parallel.

It's weird that you can actually delete babel-core and everything works... Babel 6/7 use different package names (`@babel/core` vs `babel-core`).

Related issue #232.

**Comment by queicherius** [comment]
> It's weird that you can actually delete babel-core and everything works... Babel 6/7 use different package names (@babel/core vs babel-core).

I figured out that one! I actually had installed the `babel-core` to `@babel/core` bridge while trying to fix the issue.

    "babel-core": "7.0.0-bridge.0",

**Comment by tricoder42** [comment]
Interesting! I haven't heard about this bridge. Might be useful to try out.

**Comment by jeanregisser** [comment]
Got the same error.

I was using js-lingui 2.0.7 and wanted to upgrade because of a bug that had been fixed in 2.2.0.

Because of the breaking change going from babel 7 to 6, it would have been much better for the users of js-lingui to mark that important change explicitly in the changelog and bump the major version number (assuming this lib follows [semver](https://semver.org/)).

**Comment by tricoder42** [comment]
Hey @jeanregisser, you're right. I did a mistake when I upgraded to Babel 7 and I didn't realize it would break with Babel 6. As this change was made in patch release, I had to take it back. Now I'm trying to figure out how to support both versions of babel. babel-core bridge might be solution. I'll give it a try soon.
