### ISSUE TITLE
extract of concatenated strings not working

### ISSUE THREAD

**Issue by karlhp** [lingui/js-lingui#265]
Messages in source code:

```
    const msg2 = i18n._('MSG 2 - Lorem ipsum dolor sit amet, consectetur ' +
        'adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ');

    const msg3 = i18n.t`MSG 3 - Lorem ipsum dolor sit amet, consectetur 
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore`;

    const msg4 = i18n.t`MSG 4 - Lorem ipsum dolor sit amet, consectetur\
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore`;
```
Extracting the messages with "npm run extract" creates following messages in JSON files:

```
{
"MSG 3 - Lorem ipsum dolor sit amet, consectetur  adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore": {
    "translation": "MSG 3 - Lorem ipsum dolor sit amet, consectetur  adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore",
    "origin": [
      [
        "src/pages/index.js",
        42
      ]
    ]
  },
  "MSG 4 - Lorem ipsum dolor sit amet, consectetur\\ adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore": {
    "translation": "MSG 4 - Lorem ipsum dolor sit amet, consectetur\\ adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore",
    "origin": [
      [
        "src/pages/index.js",
        45
      ]
    ]
  }
```

**msg2** is missing, extract looks to ignore string concatenation.

**msg3** is in question. Shouldn't the translation value contain a line break between the 1st and 2nd line since is a template literal?

**msg4**, the first line ends with a line continuation (\\) which means the two lines in the template literal should be interpreted as a single string without a line break as opposed to msg3. I think in this case the continuation line shouldn't be shown in the translations at all. Respectively it should show a single string without the backslash (\\), exactly as for msg2 which is currently missing.

An interesting observation is that the messageId and translate value are not necessarily the same string.

**Comment by langpavel** [comment]
Are Babel plugins in right order?

**Comment by tricoder42** [comment]
**msg2** is really missing. I'm afraid this gonna be tricky.

**msg3** this is intentional. There's a [test case](https://github.com/lingui/js-lingui/blob/7172ca848ce5a249600bbb3a66e850127ba60b49/packages/js.macro/test/fixtures/t/actual.js#L6) which checks if we replace newlines with single space. We had a discussion back then that translation shouldn't preserve any string formatting.

In JSX it's obvious - we need to be consistent how JSX works (new lines are removed and not even replaced with a space). For example:

```jsx
<span>
  multiline
  <strong>string</strong>
</span>
```

results in `<span>multiline<strong>string</strong></span>`. jsLingui follows this convention.

Question is, how to handle newlines/whitespace in plain strings. Your example:

```js
const msg3 = i18n.t`First line
        second line`;
```

should actually be `First line\n        second line` if we're about to preserve whitespace, which is exactly why it's normalized to `First line second line`. However, I've never heard about **msg3** - backlash to indicate continuation. If there's any convention how template strings are handled, we should follow it...

**Comment by karlhp** [comment]
It's not a serious problem if **msg2** isn't supported. **msg3** is okay then, it makes sense as you explain it. **msg4** is about LineContinuation and LineTerminatorSequence as described here:

https://stackoverflow.com/questions/37321047/wrap-long-template-literal-line-to-multiline-without-creating-a-new-line-in-the

http://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components

**Comment by tricoder42** [comment]
Good to know. Question still remains, how to handle leading whitespace... I don't think it's practical to include it in message, so we could:
1. without LineContinuation  - include newline, remove leading whitespace
2. with LineContinuation - remove newline, remove LineContinuation (`\`) and also remove leading whitespace

What do you think?

**Comment by karlhp** [comment]
1. without LineContinuation - sounds correct.
2. with LineContinuation
```
const msg3 = i18n.t`This is a continious\
        line`;
```
should become:

```
message = 'This is a continious line'
```
The leading white space is pretty much confusing in case of a LineTerminatorSequence. Should there be no space at all, just one space or all leading spaces? I think Chrome inserts a single space between the two lines and the sounds right to me. I'll recheck and let you know.

**Comment by tricoder42** [comment]
It does.

My only concern is that we shouldn't assume the string is going to be used only in HTML. Core library should work anywhere, even in node. Still, I can't think of usecase when leading whitespace would be actually useful. I'm just trying to figure out what to do if somebody actually needs this edge case... but we can deal with it anytime later.

Thanks for your input! Since this is potentially breaking change, let's ship it with upcoming 3.0 release.

**Comment by karlhp** [comment]
Thanks, that sounds fine. I can't think of a leading white space use case either, not sure what they had in mind to handle it this way.

**Comment by tricoder42** [comment]
Fixed and waiting for v3 release.
