### ISSUE TITLE
Spaces are added on new line in JSX

### ISSUE THREAD

**Issue by quentez** [lingui/js-lingui#268]
**Describe the bug**
With multiple lines in a `<Trans>` element, spaces are added between the lines.

**To Reproduce**
Put the following content inside a `<Trans>` element:

```
Copy &quot;
{name}
&quot;
```

**Expected behavior**
There should be no spaces between the quotes and the `name` variables.
(Standard JSX behavior).

**Additional context**

- jsLingui version ``2.4.1``
- Babel version ``7.0.0-bridge.0``
- Babel + TypeScript.

**Comment by langpavel** [comment]
It may be connected with #265. Lingui should use preprocessed tokens from Babel.

**Comment by Mirodil** [comment]
Hi,

I think, no need to remove a space between line brakes because with long text it would end up with different issue, in case when you put space end of a text it would not pass validation of the lint rule.
```
<Trans>
Hello
World
</Trans>
``` 
becomes `HelloWorld`, obviously you can add space between with `{' '}` code but it is extra.
When you add a space and remove lint rule, other devs can see it.

**Comment by tricoder42** [comment]
Actually, you example would be `Hello World`. That's how JSX treats newlines by default.

In these examples:

```jsx
<p>
  Multiline
  Text
</p>
<p>
  Multiline
  {_with}
  variable.
</p>
<p>
  Multiline
  <strong>with</strong>
  component
</p>
```

Only the first one has space between words. The other two have removed spaces and (as you said) you need to force it with `{" "}`.

I wanted this behavior to be consistent inside <Trans> component so I can remove all insignificant whitespace from message.

**Comment by tricoder42** [comment]
Fixed and waiting for v3 release.
