### ISSUE TITLE
Use CLDR rules for locale inheritance

### ISSUE THREAD

**Issue by ghostd** [lingui/js-lingui#280]
Hi,

I didn't find in the documentation how to handle the locale inheritance. Here what i'm looking for :
- `lingui add-locale fr fr-FR fr-BE`
- `lingui extract`
- add the translation of 'msg.id.specific' into all 3 files
- add the translation of 'msg.id.generic' only into 'fr' file (because the translation is the same for all 'fr' and other 'fr' alternative)
- `lingui compile`
- load the catalogs with something like this:
```js
let i18n = setupI18n({
  language: guessLocale(),
  catalogs: {
    fr: frMessages,
    'fr-BE': frBEMessages,
    'fr-FR': frFRMessages,
  },
})
```

**Comment by tricoder42** [comment]
@ghostd That's a good suggestion. I believe this should work out-of-the-box without any configuration, right? `fr` should be always a fallback for all `fr-*` locales and only then took into account `fallbackLocale` config, right?

**Comment by ghostd** [comment]
@tricoder42 exactly, this is how CLDR defines the locale hierarchy.

For now, i'm going to duplicate the translations but i think i have only 10% of specific translations... 90% could be shared.

**Comment by tricoder42** [comment]
What if you set `fallbackLocale` to `fr` as a workaround?

**Comment by ghostd** [comment]
Actually, i have 6 languages: en, es, it, fr, de, nl... (each with 2 or 3 countries) so the fallback will be not enough :-/

**Comment by tricoder42** [comment]
Hmm, that's unfortunate... I'm doing a release today or tomorrow, so I'll include it. It's potentially breaking change, but I believe if anyone used it as defined in CLDR, they would already report the bug as you did.

**Comment by ghostd** [comment]
I dont want to urge you :)

Here is a Yahoo library handling the parent locale for the CLDR data:
https://github.com/yahoo/formatjs-extract-cldr-data

I think we should check the implementation detail to follow the standard. In my case, split on '-' and '_' would be enough to find the parent, but i don't know every corner case.

**Comment by ghostd** [comment]
I dug into the [code](https://github.com/yahoo/formatjs-extract-cldr-data/blob/52d6c05a0c1e206c4022d31ee0e2f580b7085d5e/lib/locales.js#L58) and the [special CLDR data](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/parentLocales.json)

I'm not sure we really need this part. Split on '-' should be enough to find the parent.

BTW, did you mind to normalize the locale when we type `lingui add-locale`? fr-FR and fr-fr should be the same catalog.

**Comment by MrLoh** [comment]
Hi, I'm pretty unexperienced with internationalization and have a special use-case where I want to create pseudo locales for white label app deployments. So instead of e.g. `en-US` and `en-UK` I want custom identifiers like `en-Client1` so I can have different version of the same language. Should this be possible out of the box, or are only 'real' locales supported. (Luckily I only need to support one language right now, so I can get buy with one general fallback for now).

**Comment by tricoder42** [comment]
@MrLoh What is `white label app deployment` if I may ask?

As far as I know, you only need to use known language (i.e. the first part of locale), but then you can use any prefix, like `en-dev` or `en-Client1`. `xyz` would fail, because language `xyz` doesn't exists. Also, if you're looking for pseudolocalization, checkout [docs](https://lingui.js.org/tutorials/cli.html#pseudolocalization).

@ghostd Oh my, I completely forgot about this issue.

> BTW, did you mind to normalize the locale when we type lingui add-locale? fr-FR and fr-fr should be the same catalog.

Yes, please. Is there any standard for this? Should we normalize it to `fr-FR` or `fr-fr`?

Anyway, I `next` version I wanted to:
1) automatically resolved fallbacks according to CLDR data
2) allow overriding it in config, sth like:

```json
{
  fallbackLocales: {
    "en-GB": ["en-US", "en"]
  }
}
```

Anyway, fallback should be resolved at `compile` time, so we always load just flat catalog in production.

**Comment by MrLoh** [comment]
@tricoder42 that should fit my bill, thanks for the super quick reply. 

FYI: With white label app deployment I mean, that we develop one (react native) app codebase, which we then publish as several distinct apps with a different app-ID, Icon, Theme, texts to the App Store for each of our clients.

**Comment by tricoder42** [comment]
I see! That way you can ship customized locales to each customer. Interesting! Thank you for sharing 👍

**Comment by longlho** [comment]
Since we just went thru this w/ `react-intl`, just FYI there's also legacy aliases: https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/aliases.json (e.g `zh-CN` & `zh-TW` should resolve to `zh-Hans` & `zh-Hant` instead of just `zh`)

**Comment by mcwebb** [comment]
For anyone who's interested in a temporary (and hacky) workaround, you can run this as a post install script:
```
# change locale catalog fallback to base langauge
sed -i '' 's/config.fallbackLocale/language/g' node_modules/@lingui/cli/lingui-compile.js
```
