### ISSUE TITLE
Add command to watch for changes in source files and catalogs

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#349]
This is a [HactoberFest](https://hacktoberfest.digitalocean.com/) issue! Read the [contest details](https://hacktoberfest.digitalocean.com/details) for more info.

**Before you begin:**

- Confirm that you're working on this issue so I can add [👩‍💻assigned](https://github.com/lingui/js-lingui/issues?q=is%3Aopen+is%3Aissue+label%3A%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBassigned) label.
- Use `next` branch as a base for your PR. This feature should be released in upcoming [v3](https://github.com/lingui/js-lingui/issues/334).
- Read the [contribution guide](https://github.com/lingui/js-lingui/blob/master/CONTRIBUTING.md) for info how to setup project, run tests and use development version of packages
- Join us on [gitter](https://gitter.im/lingui/js-lingui) to get support

**Is your feature request related to a problem? Please describe.**
It's a bit repetitive and boring to run `lingui extract; lingui compile` to get the latest compiled message catalog.

**Describe the solution you'd like**
I think we could add `lingui watch` command which does two things:

1. Watches source files and runs `lingui extract` if something changes (path to source file is configured as `srcPathDirs`, see example in [`lingui extract`](https://github.com/lingui/js-lingui/blob/master/packages/cli/src/lingui-extract.js#L68) command.
2. Watches message catalogs (`locale/*/messages.json`) and runs `lingui compile` if something changes (path to message catalogs is hardcoded in [catalog api](https://github.com/lingui/js-lingui/blob/master/packages/cli/src/api/catalog.js#L37). It should be probably exposed to `lingui-watch` command.)

**Describe alternatives you've considered**
Another option is `@lingui/loader` for webpack which compiles catalogs on the fly, but we still need to run `extract` manually.

**Additional context**
- This is feature for [`@lingui/cli`](https://github.com/lingui/js-lingui/tree/master/packages/cli) package.
- @FredyC suggested [watchman](https://facebook.github.io/watchman/) might be useful.

**Comment by fllprbt** [comment]
Hello, could I give it a try?

**Comment by tricoder42** [comment]
@fllprbt Absolutely! Thanks a lot and feel free to ping me if you need anything! 👍

**Comment by FredyC** [comment]
I would propose a bit different approach to have `--watch` argument to both `extract` and `compile`. This makes even more sense for a manually editing catalogs as you don't want those to get modified and IDE would be complaining that file has changed in filesystem. Also auto compilation can be probably useful in some scenarios, but I don't want to be forced to use it only because I want an auto extract.

And as the bonus there can be `watch` command that does both things and it can skip watching for modified catalogs and grab them directly from a memory after extraction.

Regarding the Watchman, I've used [it in this project](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/utils/watcher.ts#L27). It looks a bit scary at first, but it turned out to be very easy and I like Watchman being universal tool that can save some system resources by reusing single process for monitoring.

**Comment by fllprbt** [comment]
@FredyC duly noted. I am quite new in this lovely project so I would like to ask some questions before submitting my opinion:

Is there a possibility to autogenerate catalogue translations? I am considering the following as the typical workflow:

- add new message to source
- re/generate catalogs
- manually add the translation
- compile

So by that notion, wherever I want to add something new I have to provide translations so that the compile operation produces any tangible effect on the project. 

Is there any other use case scenario which I am missing? If not, I do agree with your approach as it minimizes the 'watching' overhead. Moreover, your proposal of fetching from memory is another good point in that direction.

**Comment by tricoder42** [comment]
@fllprbt Usually, you don't need to watch for changes in catalogs. In development mode, messages are compiled on-the-fly, so as long as you're using source language, you're good.

If you want to see translated messages, you need to:

1. Run `lingui extract` to generate source catalog
2. Manually add translation
3. Run `lingui compile` to get compiled catalog (unless you're using `@lingui/loader`)

So, you need `lingui watch` only if you're working with other than source locales.

@FredyC What about `lingui extract --watch` and `lingui extract --watch-compile`? Adding `--watch` both to `lingui extract` and `lingui compile` will require a combined watch command anyway.

**Comment by FredyC** [comment]
> @FredyC What about `lingui extract --watch` and `lingui extract --watch-compile`? Adding `--watch` both to `lingui extract` and `lingui compile` will require a combined watch command anyway.

I don't see how it would make sense to run `lingui extract --watch-compile` if I want auto compile only? Seems rather confusing to be actually executing extract command imo.

**Comment by AOHUA** [comment]
Any updates on this feature?

**Comment by fllprbt** [comment]
@AOHUA Yes, I am still on it but I am really busy. Would you like to contribute or you are interested about the feature's delivery? If you are after the former, I could share you the existing developments.

**Comment by AOHUA** [comment]
@fllprbt I would like to help if the tasks can be separated. I also want to know if in the mean time is another way to run `lingui extract` before we push the code to our branch(except git hook)? Because right now before every push we will need to run `lingui extract` and `lingui compile` to extract the latest po file. Any suggestions? Thank you!

**Comment by fllprbt** [comment]
Here you are,

https://gist.github.com/fllprbt/5bd1e53a06ef4823a8e258fbf7c7913b

**linguiWatch** is the core, from utils just take the **toWatchmanDirs** function (should be tested extensively)

and also do not forget to add `  .command("watch", "Watch for changes in source files and catalogs")`

in your **lingui.js** so that the actual thing runs.

I am afraid I cannot help you with your second question. I had a really hard time to deploy and setup my env :(.

**Comment by FredyC** [comment]
Well, I think it would still be useful to watch for changes and extract. I often forget about it and there is no way to be warned about missing some extracted string. Having a capacity for I would certainly try to do it, but sadly not :/
