### ISSUE TITLE
Marcos id generator

### ISSUE THREAD

**Issue by antonlyaptsev** [lingui/js-lingui#402]
**Is your feature request related to a problem? Please describe.**
-
Consider existing implementation macros generates id from default translation if no key provided
```js
t`Attachment ${name} saved`

/*i18n*/{
  id: "Attachment {name} saved",
  values: { name }
}
```

It can be frustrating when the project uses file structure like this:
```
- common
  | - BuyButton
    | - index.js
- desktop
  | - BuyButton
    | - index.js
- touch
  | - BuyButton
    | - index.js
```
Developer should use different custom id in each BuyButton and keep in mind all of them
```js
// common/BuyButton/index.js
t('buy-button.common')`Buy ticket`

// desktop/BuyButton/index.js
t('buy-button.desktop')`Buy ticket`

// touch/BuyButton/index.js
t('buy-button.touch')`Buy ticket`
```

**Describe the solution you'd like**
-
I found experimental feature of `babel-plugin-macros` that can solve problem and improve developer experience (https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#config-experimental) by using custom id generator in config. It can looks like:
```js
// babel-plugin-macros.config.js
module.exports = {
  jsLingui: {
    id(expression, file) {
      // your code here
    }
  }
}
```
which produce something like this
```js
// desktop/BuyButton/index.js
t`Buy ticket`

/*i18n*/{
  id: "Buy ticket|desktop",
  defaults: 'Buy ticket'
}
```

**Describe alternatives you've considered**
-
Other alternatives was connected with writing own marcos with reusing some parts of `@lingui/macro`. But loosing support is not appropriate for my project

**Additional context**
-
no

I can make a PR. Are you interested in this feature?

**Comment by tricoder42** [comment]
Hey @antonlyaptsev, although I don't sympathise with it, I saw similar requests in other issues.

# Implementation

## Config

All macros run at build time, which means we have access to filesystem and we could load [Lingui config](https://lingui.js.org/ref/conf.html) directly. Macros config is still experimental and I saw few comments where @kentcdodds mention, we would like to move away from them. On top of that, having a single config for all Lingui related features is definitely better. Also, in the future I would like to read more config in macro (e.g. whether messages should be replaced with translations at build time).

Using JSON config:

```json
{
  "extractId": "./config/i18n-id.js"
}
```

Using JS config:

```js
module.exports = {
  extractId: function (message, filename) { ... }
}
```

You can use [`getConfig`](https://github.com/lingui/js-lingui/blob/master/packages/conf/src/index.js#L75) from `@lingui/conf` package:

```js
import { getConfig } from "@lingui/conf"

const config = getConfig()
// config.extractId(...)
```

We should also import the module and use the default export if the `extractId` is a string.

## API

I think we should pass just the message descriptor instead of whole expression:

```
type MessageDescriptor = {
  id: string,
  defaults: string,
  comment: string
  origin: Array<[string, int]>
}

export default function extractId(message: MessageDescriptor, filename: string): MessageDescriptor {
   ...
}
```

Finally, let's also return message descriptor with updated ID. In the future I would like to add `context` prop, which is used in gettext to similar usecases you have (e.g. you have the same message, which should have different meaning depending on context). In PO file, context is specified using `msgctx`:

```po
msgctxt "common"
msgid "Buy ticket"
msgstr ""

msgctxt "desktop"
msgid "Buy ticket"
msgstr ""

msgctxt "touch"
msgid "Buy ticket"
msgstr ""
```

If we return full message descriptor, users can decide if they create a unique ID prop or use context.

## Scope

- [ ] Add `extractId` to `@lingui/conf`
- [ ] If extractId is a string, load the module and use default export
- [ ] In macro, check if `extractId` is a function and if so, run `props` through it (message descriptor is a `props` variable. Right now the implementation is terrible and JS/JSX macros have a lot of duplicated logic. For JS macro, it's [here](https://github.com/lingui/js-lingui/blob/master/packages/macro/src/js.js#L282) and for JSX, it's [here](https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-transform-react/src/transformer.js#L365). 

- [ ] Add `extractId` to documentation (I'm happy to help with formatting, feel free to submit just content if you don't know reStructured Text)
- [ ] **(optional)** Write a short guide how to use this feature (motivation and simple example).


Please don't take what I've just written as a final decision. I just wanted to sort my thoughts so I wrote it down. Any feedback to config, implementation, or API is welcome. Thank you for bringing this up 👍
