### ISSUE TITLE
work with storybook

### ISSUE THREAD

**Issue by primozs** [lingui/js-lingui#413]
I cant make lingui work with storybook.

Anybody else have this issue?

Maybe I am just lacking documentation?

I tried:
- Same babel config as in dev.
- global and local custom storybook lingui provider
- adding @lingui/babel-plugin-transform-js @lingui/babel-plugin-transform-react to storybook custom webpack config and in storybook custom babelconfig.

Any ideas?
Cheers

**Comment by stereobooster** [comment]
here you go https://github.com/stereobooster/react-lingui-example/tree/storybook

**Comment by primozs** [comment]
@stereobooster Hello, thank you for an example!
For current version I had to make the storybook provider a bit differtly. For reference:
```
import React from 'react';
import PropTypes from 'prop-types';
import { I18nProvider } from '@lingui/react';
import { setupI18n } from '@lingui/core';

export function getLocaleMessagesData(language = 'en') {
  let catalog = require(`@lingui/loader!../src/locales/${language}/messages.po`);

  return {
    locale: language,
    catalogs: {
      [language]: catalog
    }
  };
}

const Pr = ({ data, story }) => {
  const defaultLocale = 'sl';
  let localeData = data || getLocaleMessagesData(defaultLocale);

  const i18n = setupI18n({
    language: localeData.locale,
    catalogs: localeData.catalogs
  });

  i18n.activate(defaultLocale);

  return <I18nProvider i18n={i18n}>{story}</I18nProvider>;
};

Pr.propTypes = {
  story: PropTypes.any,
  data: PropTypes.object
};

Pr.defaultProps = {};

export default Pr;

export const withIntl = story => {
  return <Pr story={story()} />;
};
```

Cheers!

**Comment by couds** [comment]
Hi Im trying to setup lingui with storybbok with knob addon to select the current language. (So I can use storybook to check how the component will look on diferent languages easily, I had setup a decorator like to change the language, I added all catalogs to the provider on setup because for storybook I dont need split code for that. But I cant get the storybook to reflect the change of the language

Here my setup

.storybook/config.js
```jsx
addDecorator(story => {
  const en = require('../modules/locales/en/messages');
  const es = require('../modules/locales/es/messages');

  const catalogs = { en, es };

  return (
    <MemoryRouter>
      <I18nProvider catalogs={catalogs} languages={select('Locale', { English: 'en', Spanish: 'es' }, 'es')}>
        {story()}
      </I18nProvider>
    </MemoryRouter>
  )
});
```
and I have this component where I'm testing the translation

```jsx
<p>
  <a href="https://hireflix.com/terms-candidates" rel="noopener noreferrer" target="_blank">
    <Trans id="terms">Terms 3</Trans>
  </a>
  <em>
    /
  </em>
  <a target="_blank" href="https://hireflix.com/privacy-policy-candidates" rel="noopener noreferrer">
    <Trans id="privacy">Privacy</Trans>
  </a>
</p>
```

I inspect the i18n with `JSON.stringify($r.props.i18n._catalogs, null, 2)` on the Trans node, and as you can see on the image the language on the provider its correctly set.

![image](https://user-images.githubusercontent.com/2903371/56036114-535c1a80-5d2c-11e9-988a-baa9ae266597.png)
![image](https://user-images.githubusercontent.com/2903371/56036188-7d154180-5d2c-11e9-810b-2e92441f468d.png)

```json
"{
  "en": {
    "messages": {
      "terms": "Terms",
    },
    "languageData": {}
  },
  "es": {
      "terms": "Terminos",
    },
    "languageData": {}
  }
}"
```

- If I use the Trans from `@lingui/macro` I got the default value rendered `Terms 3`
- If I use the Trans from `@lingui/react` I got the id rendered `terms`

when I change the know the element its re-rendered (I test it puting a Math.random inside the render method and I got diferents values each time I change the know language)

Can you give me a hand? I don't know what else to do.

Thanks!

**Comment by HichemBenChaaben** [comment]
I like the idea and i just wrote a custom addon for this to test language switch within storybook

https://www.npmjs.com/package/storybook-addon-linguijs

**Comment by tricoder42** [comment]
@HichemBenChaaben Nice! Would you like to add it to the docs?

There's no section for it, so what about if we create [a new section](https://github.com/lingui/js-lingui/new/master/docs/misc) called `Tooling` (`docs/misc/tooling.rst`) and start listing 3rd party libraries there?

The documentation is in RestructuredText format, but feel free to sketch it and I'll finish it 👍

**Comment by HichemBenChaaben** [comment]
@tricoder42 Sure i'll do ! 👍
