### ISSUE TITLE
Bug: HTML entities in auto-generated IDs

### ISSUE THREAD

**Issue by stephanschubert** [lingui/js-lingui#417]
I'm unsure whether this is a bug in `lingui` or in `gatsby` but my guess is that's an issue that should be fixed/considered here in any case:

**Bug description**

HTML entities in the default message are used for the auto-generated IDs:

```jsx
import { Trans } from "@lingui/macro";
export default () => <Trans>&larr; Previous</Trans>
```

Running `lingui extract` results in:

```json
{
  "← Previous": "← Previous"
}
```

Running `gatsby develop` results in the following error (_scroll right_):

```
error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "_sitePluginConnectionPluginOptionsCatalogsEnMessages←PreviousQueryString_2" does not.
```

**Expected behavior**

IMHO HTML entities should be stripped from the message IDs.

Or even better and future-proof: 
* Provide an option to specify (regex or function) for sanitization.

**Additional context**

- `lingui@2.7.2`
- `babel-core@6.26.3`
- Latest Gatsby

**Comment by tricoder42** [comment]
Hey @stephanschubert,
this is already fixed in https://github.com/lingui/js-lingui/pull/344/commits/fe0e2c852aaecce79d66541ed9608fb0256d5a98 but waiting for v3 to release. The fix should be probably considered breaking change, because it changes generated messages which might result in review of message catalogs.

The fix keeps any html entities as a part of message, e.g: `<Trans>&larr; Previous</Trans>` becomes `&larr; Previous` in catalog.

I scheduled extra time to finish v3 during Christmas holidays. Subscribe to #334 if you want to get notified when it's released.

**Comment by stephanschubert** [comment]
@tricoder42 Ah okay, great 👍
