### ISSUE TITLE
Compile po files to JSON

### ISSUE THREAD

**Issue by Skippidar** [lingui/js-lingui#474]
**Is your feature request related to a problem? Please describe.**
In big projects i don't want to include all translations to bundle, i'd like to use only necessary translation, but now "lingui compile" compiles messages to js module format only

**Describe the solution you'd like**
It would be great to be able to set output format of compiled files
1) JSON - just build json formatted messages object to be able to fetch it when app is mounted and use it's parameters
2) JS file with function, returning messages object. To be able to set it as <script src=".../messages.js"></script> and then execute window.getMessages (or any other name) to get messages array;

**Comment by cipix2000** [comment]
As far as I know there's no solution for splitting the translations per bundle. Different people use different solutions - this is one of them that I'm familiar with: https://github.com/SectorLabs/lingui-multi

**Comment by tricoder42** [comment]
@cipix2000, it looks like `lingui-multi` splits source catalogs and then (probably) creates production catalog for each of them. I'm working on the first part (splitting of source catalogs) in #326. I would like to have production catalogs generated automatically based on chunk stats, but there's lot of things to figure out.

@Skippidar Thanks for suggestion! I'm not sure how output file format is relevant. It's still going to be just one file, isn't it?

**Comment by Skippidar** [comment]
@tricoder42 Yes, i think just one file. Just to be able to load it as vocabulary. Now i do this just adding <script> tag for each file i need ant when they load i add their data to global object window.languageSettings.

The other problem is that i have several translation files - one "main" and one file per lib i have (local lib), so i have to load
/apps/[appName]/locales/en/messages.js
/libs/[libName1]/locales/en/messages.js
.....
/libs/[libNameN]/locales/en/messages.js
and then split their data.

**Comment by tricoder42** [comment]
> The other problem is that i have several translation files - one "main" and one file per lib i have (local lib, cos I have several apps, and their common parts are in libs folder), so i have to load
> /apps/[appName]/locales/en/messages.js
> /libs/[libName1]/locales/en/messages.js
> .....
> /libs/[libNameN]/locales/en/messages.js
> and then split their data.

That's exactly the problem I would like to solve very soon. First step is finish #326. That would allow you to configure source of messages - either your code or catalogs from 3rd party libs. As a result, you'll have a message catalog with yours messages and 3rd party messages, where all 3rd party ones will be translated by default. You'll be allowed to override their translations if needed.

Next step is #503, splitting the message catalog in production.

Compiling message catalogs into JSON instead of JS module is planned as well. I haven't wrote RFC yet, but it was mentioned in #334. Basically the compilation to JS should be optional and you should be allowed to do it either at runtime (with messages loaded in JSON) or build time (with messages compiled and then loaded as JS module).
