### ISSUE TITLE
Upgrade to babel 7

### ISSUE THREAD

**Issue by mschipperheyn** [lingui/js-lingui#481]
**Is your feature request related to a problem? Please describe.**
I am trying to set up a mono repo based on @babel 7. I'm encountering issue with version conflicts of core-js that are caused by @lingui depending on babel 6. Bridging doesn't work because of the lower level dependency on core-js which significantly changed its structure between v2 and 3.

**Describe the solution you'd like**
Upgrade to babel 7.

**Describe alternatives you've considered**
I've been trying to eliminate other babel 6 dependencies in my repo but I get stuck on @lingui. I get errors such as `Error: Cannot find module 'core-js/library/fn/get-iterator'`

**Additional context**
@lingui 2.7.4

**Comment by tricoder42** [comment]
Hey @mschipperheyn, could you please paste full dependency list for core-js?

```sh
yarn why core-js
```

I'm afraid we can't simply upgrade to Babel 7, because lot of people still use it. `@babel/core` is a peer dependency, so it shouldn't pull unwanted libraries unless you install them. You can choose between `@babel/core@bridge` (for v6) and `@babel/core@^7.0.0`. In `next` branch I made few changes, namely `babel-plugin-macros` is peer dependency.

**Comment by tricoder42** [comment]
LinguiJS 3 uses Babel 7 by default. See #537
