### ISSUE TITLE
Ignore compiled catalogs?

### ISSUE THREAD

**Issue by dcorb** [lingui/js-lingui#484]
In the documentation says that is safe to ignore the *compiled* catalogs ? `locale/**/*.js `https://lingui.js.org/guides/excluding-build-files.html

It doesn't make sense to me. I understand is ok to ignore ` _build` folder, but why to ignore the compiled `.js ` catalog that should be normally should be committed and loaded in production?

**Comment by zenyr** [comment]
I _used to_ include .js catalogs in git but soon I found out that I want to build a fresh copy of .js catalogs from external .json files on each build anyway.

**Comment by filipcro** [comment]
It is an auto generated file and you need to recreate it after each change anyway. You don't lose anything if you delete this file, because original translation files are enough to recreate it.

If you commit it you will produce conflicts, which somebody will need to solve, in this minimized and transpired (basically unreadable to human) file. Do you really want this? And this will happen often on project with multiple developers. Just think how often you add new translations to catalog. 

Also if you have workflow where you for some reason commit builded files to git, all files for deployment, including translations will be in root `build` folder anyway.

**Comment by dcorb** [comment]
@zenyr  @filipcro  thanks for your answers. It has sense to add the compilation step to the CI
And it's true that is creating git conflicts sometimes (easily dismissed re-generating the compiled catalog)

But the doc says it's "safe" to ignore them, without giving explanations... if you git-ignore it, and you deploy your git repo content, translations will not work (aka, it's not "safe"). You need to run that compilation step

I consider only correct to say "it's safe" to ignore the _build folder. The compiled .js files don't live inside the build folder.

![image](https://user-images.githubusercontent.com/881333/56476484-f6d1cb80-64a0-11e9-84b4-39a175cce0e8.png)

**Comment by filipcro** [comment]
If you have CI make it run compilation.

**Comment by tricoder42** [comment]
Hi @dcorb, I consider compiled catalogs as build artifacts. I don't include production bundle (e.g. next.js `_next` folder or CRA `build` folder) in git, so I don't include `messages.js` either.

The documentation could be improved though. Would you like to send a PR?
