### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by AndrewIngram** [lingui/js-lingui#49]
I'll expand this with issues as I find them, some may be unique to my project, so please bare with me:

1. When React Native's builder transforms the source files with Babel, it seems to fail when trying to transform the imported `lingui-react` module. The transform succeeds if I remove the `lingui-react` babel preset, and fails if I use it.

2. The provided components default to using `<span>` which doesn't exist with React Native, if it's possible to detect the environment, it should use `<Text>` instead, and pass through the `style` prop rather than `className`.

**Comment by AndrewIngram** [comment]
If it turns out that the branching logic is unnecessarily complex, it might be worth having a separate lib for react-native instead. At the moment I'm just exploring whether js-lingui is a viable alternative to react-intl for React Native use.

**Comment by tricoder42** [comment]
Thank you very much! 👍 

So far it seems that switching `spans` for `Texts` might be enough (+ support for style prop), so it should be easy fix. I would rather have one lib which works in both environment than two separate libs. We'll see what's the easier way...

**Comment by tricoder42** [comment]
🤔  `react-intl` solves this using `textElement` prop in `IntlProvider`: https://github.com/yahoo/react-intl/issues/600

**Comment by AndrewIngram** [comment]
That approach makes sense to me

**Comment by tricoder42** [comment]
Sorry, I was busy with my job and didn't get any chance to work on this issue. I'll continue after 13th August as I'm going on a vacation now.

**Comment by tricoder42** [comment]
Added `defaultRender` option to`I18nProvider` in latest `lingui-react@1.1.0` release.

**Comment by tricoder42** [comment]
I've just tried adding `lingui-react` to React Native app and it works.

I had to update `babel-preset-react-native` to latest release, otherwise babel tried transform files in `node_modules` as well (which raises Transform error on one file from lingui-react).

```json
{
  "presets": [
    "react-native",
    "lingui-react"
  ]
}
```

All I had to do was add I18nProvider and set defaultRender prop:

```jsx
import React from 'react'
import { Provider as ReduxProvider } from 'react-redux'
import dev from 'lingui-i18n/dev'
import { I18nProvider } from 'lingui-react'
import {Text} from 'react-native';
import configureStore from './configureStore'

import Application from './screens'

const Provider = ({ store, children }) =>
  <ReduxProvider store={store}>
    <I18nProvider
      language="en"
      catalogs={{en: {}}}
      development={dev}
      // This is required for react-native
      defaultRender={({ translation }) => <Text>{translation}</Text>}
    >
      {children}
    </I18nProvider>
  </ReduxProvider>

const store = configureStore()
export const rootNavigator = new Application(store, Provider)

rootNavigator.run()
```

Now I can use <Trans> component as usual:

```jsx
// This will render <Text>Login</Text>
<Trans>Login</Trans>
```

In components, I usually have to use custom rendering element anyway to pass some props:

```jsx
<Trans render={<Text pointerEvents="none" style={s.buttonText} />}>Login</Trans>
```

It would be great if there were some shortcut for passing props... Something like:

```jsx
// other than `Trans` props are passed down to rendered component
<Trans pointerEvents="none" style={s.buttonText}>Login</Trans>

// For plurals, selects and other i18n components, we would have to wrap them inside <Trans> component
<Trans pointerEvents="none" style={s.buttonText}>
  <Plural value={count} one={Book} other={Books} />
</Trans>
```

However, I'm afraid this would backfire very soon. Adding props to Trans would be backward incompatible :/

What do you think?

**Comment by vonovak** [comment]
@tricoder42 does `<Trans>` pass props to the underlying component? If so, you should be able to do 

```
 <ReduxProvider store={store}>
    <I18nProvider
      language="en"
      catalogs={{en: {}}}
      development={dev}
      // This is required for react-native
      defaultRender={({ translation, ...otherProps }) => <Text {...otherProps}>{translation}</Text>}
    >
      {children}
    </I18nProvider>
  </ReduxProvider>
```

and then your `Text` receives them

**Comment by tricoder42** [comment]
It doesn't. That's what I'm afraid to do. We can't pass *all* props, because some of them are used by Trans component itself. We could pass *all other* props, but then adding any new prop to Trans component would be backward incompatible. That's my main concern.

**Comment by vonovak** [comment]
@tricoder42 I see. This may be a dumb question, but why would I want to use the components:

```
<Plural 
  id="msg.plural"
  value={numBooks}
  one={<Trans>{name} has # book</Trans>}
  other={<Trans>{name} has # books</Trans>}
/>
```

over a function:

```
i18n.plural({ 
  value: numBooks, 
  one: `${name} # book`, 
  other: `${name} # books`
})
```

?

The function would be then used like

```
<MyText>
i18n.plural({ 
  value: numBooks, 
  one: `${name} # book`, 
  other: `${name} # books`
})
</MyText>
```

thanks a lot! really excited about RN support

**Comment by tricoder42** [comment]
Yeah, good question :)

I just found it more convenient to write: `<Trans>Hello World</Trans>` instead of `<span>{i18n.t`Hello World`}</span>`. When there're inlined components, the difference is even bigger:

```js
<Trans>Hello <strong>world</strong></Trans>

// compared to:
<span>{i18n.t`Hello ${<strong>world</strong>}`}</span>
```

(The example above isn't supported at the moment, because all i18n method return pure strings, not component trees).

Also, all i18n components are subscribed for locale/catalog changes, so even when the outside component is marked as pure, the translation will update properly. This wouldn't be possible for simple function calls. (Right now it also doesn't work for pure components *inside* translations, but we'll get there.)

I'm open to any suggestions. I want to have this library as simple as possible, but there're still some edge cases which aren't handled nicely.

**Comment by vonovak** [comment]
For other apps, the use cases might be different but personally I only have a couple components the render `Text` with some styles, and for that purpose I will only create components that are wrappers over `Trans` and that will handle most use cases.

**Comment by orarr** [comment]
This doesnt work for me in react-native with `babel-preset-react-native@4.0.0`
` "presets": ["babel-preset-expo", "lingui-react"],`

Error: 
` Unknown option: /home/mobile/node_modules/lingui-react/index.js.withI18n. `
