### ISSUE TITLE
[loader] 2.8.3 SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by rwu823** [lingui/js-lingui#511]
**Describe the bug**
Throws errors:

```
SyntaxError: Unexpected token export
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import en from "@lingui/loader!./locale/en/messages.json"
```

**Expected behavior**
Import the messages without any errors, version `2.8.0` is fine

**Additional context**

- jsLingui version `2.8.3`,

**Comment by ktunkiewicz** [comment]
I had the same issue and managed to get around it. The reason for this behaviour is that the CLI tool is choosing to use Babel 6 because some of your other project dependencies pull in babel-core@6.

Correct me if I'm wrong, but as far as I understood the Lingui works with both Babel 6 or 7 and chooses to use one of these depends on which one is available. Obviously, it prefers 6 over 7.

Anyways, when you run the CLI tool, it chooses babel 6, and because (I'm guessing now) you don't have the `.babelrc` file (I'm guessing that you use `babel.config.js`) it will not load any babel presets nor plugins.

There is a way to inject custom Babel configuration into `lingui extract` run, like this:
https://lingui.js.org/ref/conf.html#extractbabeloptions

This entry in package.json solved my problem:
```json
  "lingui": {
    "sourceLocale": "en",
    "fallbackLocale": "en",
    "localeDir": "<rootDir>/src/locale",
    "srcPathDirs": [
      "<rootDir>/src"
    ],
    "format": "po",
    "extractBabelOptions": {
      "presets": [
        "babel-preset-flow",
        "babel-preset-react",
        "@lingui/babel-preset-react"
      ],
      "plugins": [
        "transform-object-rest-spread",
        "dynamic-import-node",
        "transform-class-properties"
      ]
    }
  }
```

The above basically mimics what's in my Babel 7 config, just using the version 6 packages.
I also had to install all these packages:
```
npm install --save-dev babel-plugin-dynamic-import-node babel-plugin-transform-class-properties babel-plugin-transform-object-rest-spread babel-preset-flow babel-preset-react
```

I would love to see an option to simply **force** lingui CLI to always use Babel 7 @tricoder42 is there a way to do that?

**Comment by tricoder42** [comment]
@ktunkiewicz I believe it should be possible. There's already a [wrapper](https://github.com/lingui/js-lingui/blob/master/packages/cli/src/api/compat.js) around babel core functions, so we could conditionally import the correct package, e.g. based on `extractBabelVersion` config option.

Would you be interested in sending a PR? It should:

- [ ] Add `extractBabelVersion` to `@lingui/conf` (values 6 or 7, default 6)
- [ ] If the `extractBabelVersion` is 7, import from `@babel/core`, otherwise from `babel-core`

It's painful, but I'm afraid we can't simply ditch Babel 6... There're too many projects still using it :/

**Comment by ktunkiewicz** [comment]
Ah, I didn't read the source code of compat.js before, I see now that this simply imports Babel 6.

I'm playing with the source code now to see how to do that and it looks like this is slightly more complicated than just importing conditionally, because if it is supposed to be controlled by config option I'll have to make that config value be passed to some place where the `transform` from Babel 6 or 7 is selected.
I'll try to do it.

**Comment by tricoder42** [comment]
It's not that simple: `babel-core` is either `6.26.3` (Babel 6) or `7.0.0-bridge.0`, which imports `@babel/core` (Babel 7).

Thanks for looking into this 🙏

**Comment by ktunkiewicz** [comment]
what do you think about something like this? https://github.com/ktunkiewicz/js-lingui/pull/new/extractBabelVersion
