### ISSUE TITLE
Imported constants in <Trans> break Jest/Enzyme tests

### ISSUE THREAD

**Issue by ppozniak** [lingui/js-lingui#514]
**Describe the bug**
Everything works as usual, however tests are failing, saying that variable is not defined.
This happens only when **variable is used in \<Trans\> and it's imported from different file**.
![image](https://user-images.githubusercontent.com/13921243/58816990-934fc780-8622-11e9-91c0-4510e5d97998.png)

All fine if constant is in the same file or is a class property etc.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { Trans } from "@lingui/react"
import { SOME_CONSTANT } from './constants';

export default function App() {
   return <Trans>Hello {SOME_CONSTANT}</Trans>
}
```

```
const wrapper = shallow(<App />);
```
Run tests.

Current workaround I found is to do:
```
import { SOME_CONSTANT } from './constants';
const _SOME_CONSTANT = SOME_CONSTANT;
...
<Trans>Hello {_SOME_CONSTANT}</Trans>
```

**Expected behavior**
It should not break

**Additional context**

- jsLingui version `2.8.3`
- Babel version `babel-core@7.0.0-bridge.0`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```
{
  "presets": ["@lingui/babel-preset-react", "@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-syntax-export-default-from",
    "@babel/plugin-proposal-class-properties",
    "babel-plugin-jsx-control-statements",
    "macros",
    "react-hot-loader/babel",
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "@pages": "./src/pages",
          "@services": "./src/services",
          "@sharedComponents": "./src/sharedComponents",
          "@assets": "./src/assets"
        }
      }
    ]
  ]
}
```

**Comment by tricoder42** [comment]
Hey @ppozniak, that's really weird. Could you plase create a small repository with Jest, babel config and failing file?

**Comment by agwells** [comment]
I experienced a similar issue. The same `ReferenceError', `is undefined` error, under similar circumstances. Except I saw it when running the application (compiled for "dev" mode) rather than during Jest tests. (We don't have a Jest test that executes this code path, so I don't know whether that would have worked or not.)

#### To reproduce

```tsx
import {React} from 'react';
import {View, Text} from 'react-native';
import {Trans} from '@lingui/macro';
import {telephoneStyle} from 'src/styles';
import {CONTACT_PHONE_NUMBER} from 'src/contact-constants';

export const AreasScreen = () => {
  return (
    <View>
      <Text>
        <Trans>Please call{` `}
          <Text style={telephoneStyle}>{CONTACT_PHONE_NUMBER}</Text>
          {` `}to proceed.
        </Trans>
      </Text>
    </View>
  );
}
```

**Expected behavior**
The component displays the language string "Please call _{phone number}_ to proceed."

**Actual behavior**
When the application attempts to render this component, it crashes with an error message like this:

 ReferenceError: CONTACT_PHONE_NUMBER is not defined

#### Additional context ===

This is a React native application. We noticed this behavior when running the application in "dev" mode (i.e. doing `react-native start`). It didn't cause any problems at compile time, only at run time when the component in question actually attempted to render.

We have these library versions:

* @lingui/core: 2.9.0
* @lingui/macro: 2.9.0
* @lingui/react: 2.9.0
* react-native: 0.61.4
* @babel/core: 7.7.7

Babel config:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    'macros',
    [
      'module-resolver',
      {
        root: ['./'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          src: ['./src/'],
        },
      },
    ],
  ],
};
```

#### Workaround

We were able to work around the issue by assigning the imported constant to a local variable, and then using that inside the `<Trans>`:

```tsx
import {React} from 'react';
import {View, Text} from 'react-native';
import {Trans} from '@lingui/macro';
import {telephoneStyle} from 'src/styles';
import {CONTACT_PHONE_NUMBER} from 'src/contact-constants';

export const AreasScreen = () => {
  // WORKAROUND: assign imported phone number to a local variable
  const phoneNumber = CONTACT_PHONE_NUMBER;

  return (
    <View>
      <Text>
        <Trans>Please call{` `}
          <Text style={telephoneStyle}>{phoneNumber}</Text>
          {` `}to proceed.
        </Trans>
      </Text>
    </View>
  );
}
```
