### ISSUE TITLE
Lingui ignores whitespace in multi-item Trans tags

### ISSUE THREAD

**Issue by aldeka** [lingui/js-lingui#525]
**Describe the bug**
Any whitespace following a span wrapped by a lingui `<Trans>` tag is removed, contrary to React's own behavior.

**To Reproduce**

In React, the following markup

```js
<h2>
        {'Welcome '}
        <span className="name">{name}</span>
        {' to your website.'}
</h2>
```
produces "Welcome Jane to your website."

When wrapped with a lingui Trans tag, like so:

```js
<h2>
        <Trans>
                {'Welcome '}
                <span className="name">{name}</span>
                {' to your website.'}
        </Trans>
</h2>
```
the output is "Welcome Janeto your website." -- the space after the span is removed.

**Expected behavior**

I expect a single space to remain after the node inside the Trans tag.

I've tried `&nbsp;`ing my way out, trying multiple ways to mark up the strings, and so far I've been unable to get that wanted space to stop getting stripped out of my sentence, even with hacks!

It's both inconsistent with React's behavior and a big pain in the butt when trying to translate any sentences with variables in them.

**Additional context**
- lingui version: 2.7.4
- babel version: 7.3

**Comment by tricoder42** [comment]
Hi @aldeka, sorry for problems. This issue is already fixed in `next` branch:

https://github.com/lingui/js-lingui/blob/e9fead052517ba1deda4e3491a9389d12f93437c/packages/macro/src/macroJsx.ts#L13-L28

If you want, backport it to `master` branch and please send a PR. I believe the relevant lines are in `babel-plugin-transform-react`:

https://github.com/lingui/js-lingui/blob/f212786af02cb7c974764649e6fe7a484b20c71a/packages/babel-plugin-transform-react/src/transformer.js#L377-L380

This will fix whitespace inconsistencies in JSX macros/plugins.

---

JS macros/plugins use similar approach, so we might also want to fix that as well:

Fix in `next` branch:

https://github.com/lingui/js-lingui/blob/e9fead052517ba1deda4e3491a9389d12f93437c/packages/macro/src/macroJs.ts#L9-L17

Relevant code in `master`:

https://github.com/lingui/js-lingui/blob/f212786af02cb7c974764649e6fe7a484b20c71a/packages/babel-plugin-transform-js/src/transformer.js#L325

If you need any help with setting up the dev environment, please let me know 🙏

**Comment by bukku-accounting** [comment]
We bump into the same problem with TS.

`
        <Trans>
                {'Welcome '}
                <span className="name">Name</span>
                {' to your website.'}
        </Trans>
`

We got 

> Welcome Nameto your website.

Any clues?

lingui version: 3.13.3
babel version: 7.18.5

**Comment by andrii-bodnar** [comment]
@bukku-accounting could you please check if it's reproducible on the latest Lingui version?

**Comment by Santalov** [comment]
Reproducible in lingui 4.11.1

```JSX
            <Trans>
              Friend will get
              {' '}
              {ticketsFromReferralSystem}
              {' '}
              extra tickets
            </Trans>
```

Produces
`Friend will get5extra tickets`

**Comment by timofei-iatsenko** [comment]
Will be fixed in v5

Related PRs: https://github.com/lingui/js-lingui/pull/1882 

Note in the changelog https://github.com/lingui/js-lingui/blob/e7b95a87496ba26db85cbae3b135650737f40fd0/website/docs/releases/migration-5.md#changes-in-whitespaces-handling
