### ISSUE TITLE
when Plural macro uses id, ICU is lost within extraction

### ISSUE THREAD

**Issue by Hotell** [lingui/js-lingui#529]
**Describe the bug**

When `Plural` uses `id`, ICU format is lost when extracting translations

`lingui extract` 👉
```
#: src/app.js:19
msgid "inbox.messagesCount"
msgstr ""
```

**To Reproduce**

```js
import { Plural } from "@lingui/macro"

export default function App(props) {

   return <p>
   <Plural
      id="inbox.messagesCount"
      value={props.messagesCount}
      one="There's # message in your inbox"
      other="There're # messages in your inbox"
   />
</p>
}
```

**Expected behavior**

`extract` should pass ICU to default locale ( en ) as translation

```
#: src/app.js:19
msgid "inbox.messagesCount"
msgstr "{count, plural, one {There's # message in your inbox} other {There're # messages in your inbox}"
```

**Additional context**

- jsLingui version `2.9.3`
- Babel version `babel-core@7.0.0-bridge.0`
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)

```
const presets = [
    [
      '@babel/preset-env',
      {
        // Allow importing @babel/polyfill in entrypoint and use browserlist to select polyfills
        useBuiltIns: 'entry',
        // @see https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#usebuiltins-entry-with-corejs-3
        // Need to stick with 2 because of linaria 😭
        corejs: 2,
        // Do not transform modules to CJS
        modules: IS_TEST ? 'commonjs' : false,
        loose: true,
      },
    ],
    '@babel/preset-react',
    '@babel/preset-typescript',
    '@lingui/babel-preset-react',
  ]

  /** @type {import('babel').BabelConfigOptions['plugins']} */
  const plugins = [
    '@babel/plugin-syntax-dynamic-import',
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
    'macros',
  ]
```

**Comment by tricoder42** [comment]
Meanwhile as a workaround, can you wrap it in `<Trans>` component?

```jsx
<Trans id="inbox.messagesCount">
  <Plural
      value={props.messagesCount}
      one="There's # message in your inbox"
      other="There're # messages in your inbox"
   />
</Trans>
```

**Comment by Hotell** [comment]
That won't help.

It just extracts 2 messages, which are not bind together:

```
#: src/app.js:19
msgid "inbox.messagesCount"
msgstr ""

#: src/app.js:20
msgid "{count, plural, one {There's # message in your inbox} other {There're # messages in your inbox}"
msgstr ""
```

**Comment by Hotell** [comment]
Ups, I mismatched `current` vs `expected` behaviour. Sorry. Updated https://github.com/lingui/js-lingui/issues/529#issue-461055049

**Comment by Hotell** [comment]
So I found the culprit.

When `sourceLocale` is set, it correctly creates the key -> ICU plural

```ts
/** @type {Partial<import('@lingui/cli').Configuration>}  */
const config = {
  compileNamespace: 'es',
  format: 'minimal',
  sourceLocale: 'en',
}
```

**Output**

```
#: src/app.js:19
msgid "inbox.messagesCount"
msgstr "{count, plural, one {There's # message in your inbox} other {There're # messages in your inbox}"
```


So I suggest 2 things:
- warn consumer during `lingui extract` about that he's using id for plurals but didn't set `sourceLocale`
- even if `sourceLocale` is not set I would always fallback to `en` and create proper id<->message pair

WDYT?

**Comment by tricoder42** [comment]
> warn consumer during lingui extract about that he's using id for plurals but didn't set sourceLocale

Does it happen only for plurals or for regualar messages as well?

> even if sourceLocale is not set I would always fallback to en and create proper id<->message pair

That way we lost track which messages aren't translated. I understand it's painful when you get just ID and you don't know the default message, but that problem can be solved by several approaches:

1. Provide enough info in `description` or `msgId` so the translator can fill the  copy without the original - it sound a bit extreme, but I know at least one developer/company who does it that way. Translation isn't always 1:1 mapping from one locale to another and that way they get more accurate copy which fits the locale.

2. Use translation management tool, when you can toggle source locale - i.e. instead of having a table msgId -> target locale, you have source locale -> target locale. That way the translator don't see the msgId at all and focuses only on copy.

3. We could use `previously untranslated string` field from [gettext PO](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) format:

```po
#| msgid "{count, plural, one {There's # message in your inbox} other {There're # messages in your inbox}"
msgid "inbox.messagesCount"
msgstr ""
```

What do you think?
