### ISSUE TITLE
`defineMessage`-macro returns message when NODE_ENV=`development`

### ISSUE THREAD

**Issue by PutziSan** [lingui/js-lingui#548]
**Describe the bug**
During development `defineMessage({ id: "test-id", message: "my message" })` returns `my message` and not `test-id`. When building with `NODE_ENV=production`, everything works fine.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { defineMessage } from "@lingui/macro";

const msg = defineMessage({ id: "test-id", message: "my message" });

function App() {
  return <pre>{JSON.stringify(msg, null, 2)}</pre>;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Expected behavior**
During development `defineMessage({ id: "test-id", message: "my message" })` returns `test-id`.

**Additional context**

- jsLingui version ``3.0.0-7``
- Babel version ``7.5.5``
- CRA3 (`"react-scripts": "3.0.1"`)

PS: great work! I really like the library and v3-version.

**Comment by tricoder42** [comment]
Hey @PutziSan,
I think this issue is fixed in https://github.com/lingui/js-lingui/pull/543/files#diff-43ddbf96c9ea592d8e5253508230cd3aL160 by @hjylewis. #543 is an effort to make production and development more consistent.

Let's close it as a duplicate and reopen it, if the problem persists in next pre-release
