### ISSUE TITLE
[Feature REQ] Currency react input or currency parser

### ISSUE THREAD

**Issue by Hideman85** [lingui/js-lingui#550]
I use ant design css library and I have a [InputNumber](https://ant.design/components/input-number/#API) and with that I able to provide a formatter to render the number but I need also to provide a parser do get number from a formatted string.

I want to be able to parse a formatted currency string back to a number and be lang agnostic.

The best would be to have directly some input components with this library to allow input formatted date as Date object and formatted number/currency to Number.

**Comment by tricoder42** [comment]
Hey @Hideman85, I'm not planning adding any Date/Number components. In fact they're removed in Lingui v3 and should be provided by 3rd party modules. For example, date-fns provides parsing/formatting for dates. I believe there could be similar library for numbers. My idea is that we should just use existing libraries and hook them into Lingui instead of providing own formatting/parsing features.

**Comment by bernharduw** [comment]
@tricoder42 Just found your comment. Does this mean that eventually the `i18n.number()` function will be also removed, so formatting numbers in lingui@next as described in https://github.com/lingui/js-lingui/issues/551#issuecomment-520778712 would stop working too?
