### ISSUE TITLE
Feature Request: Custom formats of message catalogs

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#56]
Followup to #53 

Support custom formats of message catalog:
- flat JSON (only message & translation)
- nested keys JSON
- default one

**Comment by mcongy** [comment]
Just to add my 2 cents:
I like the old format more. Even tho it's not that powerful, it's enough for my use-case.
It's way more clear and shorter. Adding 9 lines for a single translation isn't acceptable for me.

Anyway, great work with the project. Just started using it and I really like it so far!

**Comment by tricoder42** [comment]
You should never create translation files manually. That's the task for `lingui extract`. However, I agree that  the new format is too complex for translators or anyone who edits the message catalogs manually.

As the project grows, it becomes inevitable to add comments/description to messages or at least know from where the message comes from. Also, some people might eventually want to use other formats, like XML or XLIFF to integrate jsLingui into their existing tools.

Thanks for the support!

**Comment by mcongy** [comment]
By "adding 9 lines for a single translation" I meant what ```lingui extract``` does. A single-word translation adds 9 lines of JSON. 

I mean this:
```
"Hello": {
  "translation": "",
  "origin": [
    [
      "src/components/pages/Hello.jsx",
      11
    ]
  ]
}
```
I do aggree that the old format isn't sufficent for a lot of use cases, but from my experience, it should be enough for a lot of people. Some people just prefer the easy solutions instead of the "correct in every possible way" solutions. And they might find the new format intimidating.

But again, that's just my point of view.

**Comment by tricoder42** [comment]
Added `lingui extract --format minimal` option to generate flat JSON.
