### ISSUE TITLE
[v3] `t` macro uses global i18n instance

### ISSUE THREAD

**Issue by janicduplessis** [lingui/js-lingui#578]
**Describe the bug**
I'm using this library on the server and create a new i18n instance for each request so they don't conflict with concurrent requests. The issue is that when using the `t` macro it seems to do more than what I expect. Instead of converting the string to a message object like mentioned in the doc it gets transformed to a call to `i18n._(message)` which returns a translated string.

Not sure if this is expected behaviour in v3 but it would make the `t` macro unusable on the server.

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
ctx.intl._(t`Hello ${area.name}`)
```
->
```
ctx.intl._(
/*i18n*/
core["i18n"]._("Hello {0}", {
  0: area.name
})),
```

This results in 2 calls of `_` function and breaks variables in translations.

**Expected behavior**
The `t` macro simply converts the message to an object that needs to get passed to an instance of i18n.

**Additional context**

- jsLingui version `3.0.0-7`
- Babel version `7.6.3`
- Your Babel config
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
        loose: false,
        useBuiltIns: false,
        shippedProposals: true,
      },
    ],
    '@babel/preset-react',
    '@babel/preset-flow',
    '@babel/preset-typescript',
  ],
  plugins: [
    'macros',
    ['@babel/plugin-proposal-optional-chaining', { loose: true }],
    ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: true }],
    '@babel/plugin-syntax-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: true,
        regenerator: false,
        useESModules: false,
      },
    ],
  ],
};
```

**Comment by janicduplessis** [comment]
I went through the commits and this change seems to be done on purpose. I think this might need to be reconsidered as it will break regular server usage as well as react server rendering as soon as there are multiple concurrent requests.

**Comment by tricoder42** [comment]
@janicduplessis Yeah, you're right. This is intentional. In the near future, I would like to generate per-locale bundles as described in #508 and for that I need to wrap message and i18n._ call into macro.

I understand that in server apps the bundle size doesn't matter and per-locale bundles are useful only in browser. So what about adding a config `macroStandalone` which would be true by default:

```
/*
 * macroStandalone: true
 */

t`Hello world`
// ↓ ↓ ↓
i18n._("Hello World")

/*
 * macroStandalone: false
 */

i18n._(t`Hello world`)
// ↓ ↓ ↓
i18n._({ id: "Hello World" })
```

That way we could configure it based on app needs.

- What do you think about this idea in general?
- Would you choose a different name for configuration option?
- Would you be willing to implement it? It should be possible to track the test case from specific commit and revert/merge it with current codebase.

**Comment by janicduplessis** [comment]
@tricoder42 Could we do something like this instead?

```
/*
 * perLocaleBundle: true
 */

intl._(t`Hello world`)
// ↓ ↓ ↓
intl._("Hello World")

/*
 * perLocaleBundle: false
 */

i18n._(t`Hello world`)
// ↓ ↓ ↓
i18n._({ id: "Hello World" })
```

**Comment by tricoder42** [comment]
There isn't much difference between these too. In both cases you need to wrap the macro to `i18n._` call. On top of that, the first wouldn't work for messages with parameters:

```js
i18n._(t`Hello ${name}`)
// ↓ ↓ ↓ Bad: Can't use macro to transform 1 AST node into a list of nodes
i18n._("Hello {name}", { name })

i18n._(t`Hello ${name}`)
// ↓ ↓ ↓ Good: Macro transforms tagged template literal (1 node) into an object literal (1 node)
i18n._({ id: "Hello {name}", values: { name } })
```

But the real question is the `i18n._` object. In `perLocale` bundles you don't need it at all, because translations are hardcoded in production bundle. Macro could potentially traverse in AST tree and remove the parent automatically, but this feel very hackish as macro shouldn't operate outside the AST node which it encloses.

That's the idea with transforming `t` macro into `i18n._` call (runtime localization) or string (compile time localization).

**Comment by janicduplessis** [comment]
Ok I see. So my issue is mainly about injecting the call to the global `i18n._`, if we can avoid that we'd keep the ability to use any i18n instance.

For runtime localization we could keep the old transform so:
```js
t`Hello ${name}`
// ↓ ↓ ↓
{ id: "Hello {name}", values: { name } }
```

For compile time localization we could use a new helper and make `i18n._` pretty much a no-op. Not sure if this is always possible but for simple cases like this example it would be possible to transform to a template string directly and have 0 runtime.

```js
t`Hello ${name}`
// ↓ ↓ ↓
i18n._formatHelper("Hello {name}", { name })
```

Or maybe

```js
t`Hello ${name}`
// ↓ ↓ ↓
`Hello ${name}`
```

**Comment by janicduplessis** [comment]
Maybe I failed to address your point properly. Part of the issue is you'd like to remove the call to `i18n._` completely for compile time localization right? If the function become a no-op at runtime for localized bundles I don't think it will really cause perf overhead if that is the concern since it will probably be easily inlined by js engines.

**Comment by tricoder42** [comment]
Hey @janicduplessis, unfortunatelly at the moment you have to use global instance with macros. You are able to use use the library *without* macros though. Maybe we'll revisit it in the future after v3 release, but right now I don't have resources to make it work.

**Comment by janicduplessis** [comment]
👍 I'll investigate using without macros where this caused issues.
