### ISSUE TITLE
Translation with variable inside does not work in production without extracted & compiled texts

### ISSUE THREAD

**Issue by vitexikora** [lingui/js-lingui#58]
Firstly, this issue only appears in production (without development prop on provider) and only if this translation wasnt extracted & compiled (just running those commands, no translation).
Having this:
```js
{i18n.t`narozen ${birthdate}`}
<Trans>narozen {birthdate}</Trans>
```
should render (and on localhost/dev renders):
narozen 8.8.1943
narozen 8.8.1943
but on productions shows:
narozen {birthdate}
narozen {birthdate}

Issue disappeared after just running extract & compile, however this shouldn't happen. I don't understand the innerworkings, but if it is not capable of rendering it correctly in production without compile, it should also fail on dev, so there is no bad surprise after deploy..

**Comment by tricoder42** [comment]
Just remove `development` prop during development and you'll get the same environment as in production. I agree this should be more obvious and documented.

`development` prop is there just for convenience so you don't have to run extract&compile every time you change some component. However, you really need compiled message catalogs in production, because ICU message parser is very heavy and slow.

I'll think about the whole workflow again. I guess the best way would be having webpack loader, which handles extracting & compilation under the hood and also creates message catalogs for production. What do you think?

**Comment by vitexikora** [comment]
Oh, I didnt know that development only runs this silently on background. Now that makes sense, so I should have these commands included in CI. 
Having a loader would be cool, but this may as well introduce more complexity to the setup, when you would have to configure location and bundling of those files.
Just include in the docs, that in production, the compile has to be run beforehand.

**Comment by tricoder42** [comment]
I'll leave it open until I update the docs
