### ISSUE TITLE
Feature request: Allow no-op/lazy translations

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#60]
Followup from #53 

Sometimes it's necessary to mark strings which will be translated in the future, but leave them intact for now:

```jsx
import { Trans, noop } from 'lingui-react'

const menu = [
  { to: '/about', title: noop('About') },
  { to: '/contact', title: noop('Contact') },
]

// later in the code
const Menu = () => 
  <div>{
    menu.map(item => 
      <Link to={item.to}>
        <Trans id={item.title} />
      </Link>)
  }</div>
```

**Comment by vitexikora** [comment]
IMHO the method should be named most closely to what it actually does, which in this case is something like 'markForTranslation/Extraction', 'addTranslation', 'linguiString', or even 'internationalize', rather than 'noop'... Looking at this example code I would have no idea what it does. Just an opinion.

**Comment by tricoder42** [comment]
Yeah I have similar concern. I know this naming from [Django](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#marking-strings-as-no-op), but there is `ugettext_noop` so you at least know that it's related to gettext.

It's basically `i18n.t` without the translation, so maybe `i18n_noop`, `i18n_mark`, `i18n_add`, `i18n_dummy`, `i18n_future`, `i18n_lazy` (it could be also considered as "lazy" translation).

From your examples I'm considering `markForTranslation` 🤔

**Comment by vitexikora** [comment]
May I ask, how is this feature looking? I am really looking forward to it 👍 😊

**Comment by tricoder42** [comment]
I was a bit busy in last few weeks, so I was happy to find at least some time to refactor cli.

However, this should be very easy, I'll take a look this week.

If you want to work on this, it's basically just:
1. Add another node matcher, similar to this: https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-lingui-transform-js/src/index.js#L7
2. Make sure, we replace node with source string, not `i18n.t` call here: https://github.com/lingui/js-lingui/blob/master/packages/babel-plugin-lingui-transform-js/src/index.js#L218

I would go with following syntax:

```js
import { i18n_noop } from 'lingui-i18n'

const languages = {
  en: i18n_noop('English'),
  cs: i18n_noop('Czech')
}
```

which would be transformed to

```js
const languages = {
  en: 'English',
  cs: 'Czech'
}
```

Question is, how to handle translations with variables? 🤔  Should `i18n_noop` support only *static* translations?

**Comment by vitexikora** [comment]
Thats ok, its still cool, you have time to improve this lib and push it further 👍 Doesnt have to be all at once..

> Should `i18n_noop` support only static translations?

Given the typical usage of such function, I guess it should not be a problem. I would make it static and create an enhancement issue with a very low priority on it supporting even variables and tags. Just to keep all functions consistent, because I can imagine (in the future) people misusing this function and wondering why it doesnt work with variables.

**Comment by tricoder42** [comment]
Alright, added in latest releases:
 - lingui-cli@1.3.2
 - lingui-i18n@1.3.0
 - lingui-react@1.2.0

The function is named `i18nMark` after all. See the [docs](https://lingui.gitbooks.io/js/ref/react.html#i18nmark) for more info.

**Comment by vitexikora** [comment]
Awesome!
