### ISSUE TITLE
react tutorial in the docs is wrong/outdated

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#687]
Screenshot from the current page here: https://lingui.js.org/tutorials/react.html
![image](https://user-images.githubusercontent.com/1305378/81210836-c4730d80-8fd2-11ea-9c1d-3ad9ff266f49.png)

this is wrong.  Even TS typings do not allow to call the `load` with two arguments.
I had top do it like this to get my catalogs working:
```tsx
<I18nProvider i18n={i18n} language={'en'} catalogs={{en: enMessageCatalog}}>
```

this took me quite some time to figure out as my app was running fine in english for development. Would be worth fixing.

I wanted to do it myself, but the file in the repo doesn't even have this bit, so maybe just republishing of the docs would suffice?

**Comment by toolness** [comment]
Oof, I ran into this problem as well!  Thanks for documenting it.

One thing I'm realizing is that the docs might actually be _too new_, not out of date!

It looks like version 3.x of lingui is in development, while what you and I are using is 2.x, because that's what's on npm.  According to the 2.x to 3.x migration notes, there is a section called [i18n.load loads a catalog for a single locale](https://lingui.js.org/releases/migration-3.html#i18n-load-loads-a-catalog-for-a-single-locale) which describes an evolution _towards_ what's currently in the React tutorial.  So the problem might not be that the docs are out-of-date, but rather that they're _so new_ they're for a version of lingui that hasn't even been released yet! Oy.

**Comment by toolness** [comment]
> I wanted to do it myself, but the file in the repo doesn't even have this bit, so maybe just republishing of the docs would suffice?

I think that the problem is that the docs on the site are actually being published from the `next` branch, not `master`--more details at #692, which I just filed!

**Comment by tricoder42** [comment]
I've just deploy docs from `master`, but @toolness is probably right that I might accidentaly update the old docs with v3 version... Unfortunately I'm not going to fix anything in master as I need to focus on releasing v3, but if you want to send a PR, I'm happy to review/merge it 👍
