### ISSUE TITLE
Add a CLI command to validate the catalog on CI

### ISSUE THREAD

**Issue by Spy-Seth** [lingui/js-lingui#722]
**Is your feature request related to a problem? Please describe.**
One of the common problem with localization process is that as a developer you have to not forgot to run `lingui extract` before committing new/edited/removed string.

**Describe proposed solution**
Add a CLI command like `lingui check-catalog` that verify that all the key of the application are present in all catalog. It will return an errored exit code if some string are not referenced in the catalogs.
 
A verbose mode could also print the location of the missing messages.

I work on it if your ok with the idea

**Comment by makenosound** [comment]
Would love this too. I’m planning on doing a manual version by comparing files before/after `extract` on CI, but it feels like a very useful bit of core functionality.

**Comment by tricoder42** [comment]
Hey @Spy-Seth, good idea!

> A verbose mode could also print the location of the missing messages.

Do you mean location of messages which weren't extracted or which are missing translations? [`lingui compile --strict`](https://lingui.js.org/ref/cli.html#cmdoption-compile-strict) already checks for missing translations.

I'm thinking if we could actually create a `lingui check` command which would run a series of checks:
- Check that running `lingui extract` won't add any new message to catalog (i.e. all messages are already extracted)
- Check that all messages are translated (we would need a way to mark messages which don't require translations)
- Anything else?

I don't mean we should implement everything now. I'm just trying to figure out if there's a usecase for additional checks. Otherwise we might also go with `lingui extract --check` or `--dry-run`.

**Comment by Spy-Seth** [comment]
> Do you mean location of messages which weren't extracted or which are missing translations?

The location of the message that need to be extracted.

> we could actually create a lingui check command which would run a series of checks:

My initial point was only focus on the missing message in the catalog. 

It's a good idea to also provide some check at compile time to detect earlier errors in the catalogs.

But given that each team have its own workflow (external translation tools, external translator, automated translation platform...) and its own quality target (for some team using a fallback on the main language is not an issue) : checking if all message are translated and the requirement should be configurable. Maybe the tolerance on missing translation are not the same in all language too. 
This subject seems more touchy than validating that all string are extracted from the source code.

Depending on the team workflow, the `lingui check` command should be able to only check the message that need to be extracted

**Comment by tricoder42** [comment]
Good points! Alright, feel free to send a PR. Could you please base it on `next` branch? Thanks a lot!

**Comment by Spy-Seth** [comment]
I will propose you something in the next weeks

**Comment by tricoder42** [comment]
Perfect! Let me know if you need anything. I'm working on Lingui again after a long period of time, so I'll be available.

**Comment by miguelCT** [comment]
I have a question related to this issue and the question asked in #629. Aren't both issues related to the fact that, when missing translations are found, the process is not exited with an error? 

In the line below, you can see that the process is exited, but not with a `1` code, so you cannot use the `--strict` flag in `compile` cli option to actually check in CI if the translation messages were forgotten by the user, because the process will always exit correctly.

https://github.com/lingui/js-lingui/blob/7f09c2d4ddd88d885a5df23e1b0c267f937abaaf/packages/cli/src/lingui-compile.ts#L81

In my opinion, that line should be: 

```js
process.exit(1)
```

What do you think about it? @tricoder42 

> PD: sorry to post in an already closed issue, but I think that it made sense. If you think that I should open another issue I'll gladly do it.

**Comment by tricoder42** [comment]
Yeah, good point! Thank you @miguelCT, could you please send a one-liner PR?

**Comment by miguelCT** [comment]
> Yeah, good point! Thank you @miguelCT, could you please send a one-liner PR?

Sorry for the delay, I was busy at work.

I've seen that a PR has already been submited! Super fast :smile: 
Thanks @semoal

**Comment by marlonjan** [comment]
Hi there, I've also observed the issue that @armandabric described, forgetting to run `lingui extract` and committing the changes seems to be quite common. As a result, changes in `.po` files often end up in later commits or even later pull requests, in which case it tends to make the code review process slightly confusing.

I found the following command quite useful to check that there are no uncommitted changes after running `lingui extract`:
```bash
yarn lingui extract && if [[ -n $(git status --porcelain | grep "messages.po") ]]; then echo "Error: Uncommitted changes in some of the .po files" && exit 1; fi
```
However, this can only work it's when executed in a git repository, which is not always the case in a CI setting. Something like `lingui extract --check` or `--dry-run` with appropriate exit codes would be very useful 👍

**Comment by landsman** [comment]
I'm currently investigate options about this.
I have prepared my own github actions - a composite type that I will be able to integrate into several projects.

So far, I'm stuck on the fact that I need `@lingui/cli` install globally. That's not a problem, problem is when I tried to use it as cli command under some project.

It's generates hundred of errors like this one:

```
Cannot process file Cannot find module 'babel-plugin-macros'
Require stack:
- /usr/local/lib/node_modules/@babel/core/lib/config/files/plugins.js
- /usr/local/lib/node_modules/@babel/core/lib/config/files/index.js
- /usr/local/lib/node_modules/@babel/core/lib/index.js
- /usr/local/lib/node_modules/@lingui/cli/build/api/extractors/babel.js
- /usr/local/lib/node_modules/@lingui/cli/build/api/extractors/index.js
- /usr/local/lib/node_modules/@lingui/cli/build/api/catalog.js
- /usr/local/lib/node_modules/@lingui/cli/build/lingui-extract.js
```

**Comment by landsman** [comment]
@tricoder42 can you please open this again? 🙏

**Comment by thekip** [comment]
@landsman 

> Cannot process file Cannot find module 'babel-plugin-macros'

This already fixed in `next` branch, and would be deployed as v4 soon. 

Regarding the original issue: 

I think the process could be changed to eliminate this checks and this issues in general: 

1. Just add extract to your build command which is called on CI
   package.json
   ```json
      "build": "lingui extract && yarn build:app",
      "build:app": "..."
   ``` 
   In this case is usually better to extract into template `lingui extract-template` because this would not touch files tracked by Git during CI

2. Add `extract` workflow to the precommit hook using `lint-staged` and `husky`.

So the question in general sounds like: 
> if you can run checking catalogs on CI why you don't just run extraction on CI directly?

**Comment by landsman** [comment]
@thekip Thanks. I'm looking for a single line task step for a github action that I can use on multiple projects. The goal is to stop the workflow for Pull Request checking the build if there are any forgotten localizations.

**Comment by thekip** [comment]
I understand your case, you doing it wrong. When you do it right you don't need validate this in any step in CI

**Comment by landsman** [comment]
You can turn off git hooks (precommit) every time you do commit via IDE. I want to check these changes on CI, via linked shell script. This is the only way to make sure that someone didn't break anything and main branch in our project will be clean for others.

**Comment by thekip** [comment]
c'mon, just do extraction on ci, you don't hear me.

**Comment by landsman** [comment]
That's how I do it, look at the github action code I sent.

**Comment by thekip** [comment]
I see that you extracting and commiting extraction results and then trying to validate that no one from developers did not forget to extract before commit. 

Do you check that your developers build/transpile your project and commit /dist folder on every commit? 

You should reason about artifacts produced by extraction process as a derivative from the code. (similarly to .js / .map files produced from your typescript). 

Just setup extracting with `extract-template` on CI **only**. And don't let developers do it. Problem is gone. 

Validating that all messages **translated** is other story that makes sense.

**Comment by justingrant** [comment]
@landsman, here's what we ended up using in CI: 

```sh
lingui extract --clean && git diff --exit-code -- '*.po'
```

> Do you check that your developers build/transpile your project and commit /dist folder on every commit?

Our `.gitignore` excludes generated files like `en.ts` or `fr.ts`, but does NOT exclude `*.po` because translations are checked into those files. We use the [Explicit ID](https://lingui.dev/tutorials/explicit-vs-generated-ids#explicit-id) strategy, so our English strings are also in a `.po` file. Are there other workflows that avoid checking in those files?

> Just setup extracting with `extract-template` on CI only. And don't let developers do it. Problem is gone.

I read the docs on `--extract` vs `--extract-template`. What is the advantages of using the latter vs. the former? 

> I'm looking for a single line task step for a github action that I can use on multiple projects. The goal is to stop the workflow for Pull Request checking the build if there are any forgotten localizations.

Unless I'm misunderstanding the proper workflow for i18n on a tiny and underfunded team, this option is useful for us too. We're familiar with (and happy with) tools like ESLint or prettier, where developers should be running `eslint --fix` before pushing PRs, but CI runs them again as a failsafe to make sure that PRs don't get merged unless developers have done what they're supposed to do.

> Validating that all messages **translated** is other story that makes sense.

Our small team doesn't translate strings in every PR. Instead, we batch up needed translation work and then translate many strings by checking in changes to `.po` files in a PR before every public release. So we'd ideally have BOTH a tool that detects missing translations in CI, and also a tool that detects missing extractions in CI.

**Comment by thekip** [comment]
> I read the docs on --extract vs --extract-template. What is the advantages of using the latter vs. the former?

Well to understand the difference we should go back to the 80s when original gettext suite was introduced. The typical flow including: 

1. Extract messages from application to the template file (.pot) with util 1
2. Merge template file (.pot) into translation files (.po) with util 2
3. Merge translations back to the apllication with util 3. 

Usually step 2 is done by special trasnlation tool, such as Po Editor, which aware of template files and usually database inside this translation tool is the first source of truth for translations. 

When lingui was designed in the first place, original author decided that step 2 is not necessary and extractor tool could take a responsibility of merge tool as well, because that seems easier at that moment for the author's flow. 

However, this brings a non-obvious consequence which in it's turn brings problems: 

- extractor tool touches files which under version control, so you have to force everyone on every commit to extract messages otherwise your catalogs not in sync. (this is your problem n1)

How `extract-template` could help with that? Simply, all artifacts produced by this command could be ignored. You can fully automate the whole i18n flow. Your translation catalogs **may not have** all messages from source code. but this is fine because it will fallback to the template. 

Example of typical workflow: 

```js
// package.json
scripts: {
  build: "lingui extract-template && app build",
}
```

Every time on CI or whenever you want to build your app template is automatically created, so you are on the safe side. 
When you want to translate strings (as you mentioned in batches), you just take the latest template merge it into existing catalogs and translate with tool such as POEditor. 

Hope this is helpful.

**Comment by justingrant** [comment]
Got it, thanks for the helpful context. 

For our app, we have <100 localized strings, are only localizing to a few langs (only EN and FR for the next year+), and our localization is performed by French-speaking colleagues. It's very informal but easy for us to manage at small scale. 

Adding a separate tool and workflow for translation may be more complexity than we want to add right now. If our company and product grows and end up having thousands of strings and a larger budget and higher expectations for i18n, then I can totally see the value in switching to the process you describe above. But for our current state, the current `.po`-only workflow seems to work pretty well and we're not eager to spend the time to change it right now. The only pain point has been ensuring that extraction happens before merging PRs, and we've now solved this by adding the one-line CI test `lingui extract --clean && git diff --exit-code -- '*.po'`. 

I suspect there are lots of small teams like ours with similar needs, so IMO it does make sense to have a `lingui` CLI option that achieves the same result as our existing CI test but has clearer console output and doesn't require actually changing files so could be run locally too.
