### ISSUE TITLE
Documentation with regards to monorepo setup is unclear

### ISSUE THREAD

**Issue by cezarneaga** [lingui/js-lingui#810]
**Describe the bug**
Not really a bug. more a documentation improvement.
https://lingui.js.org/guides/monorepo.html page content is not telling enough about how to set this up.

**Expected behavior**
Perhaps a monorepo example in the examples folder would be a minimum helpful step.

Ideally, explaining challenges and use-cases that would be covered would also be in there.
eg: if a monorepo contains an UI library and the other packages import modules from it, how would the translations be handled?

**Comment by tricoder42** [comment]
All improvements to documentation are welcome! Feel free to send the PR 👍

**Comment by cezarneaga** [comment]
> All improvements to documentation are welcome! Feel free to send the PR 👍 

Will gladly send a PR. Would however love it if we could chat for 5 min to give me the gist of it all. 

I could just experiment until i get it right but would lose a lot of time needlessly.

**Comment by gbiryukov** [comment]
Practically we are facing an issue with `.po` files resolution in monorepo. lingui webpack loader converts absolute paths to relative [here](https://github.com/lingui/js-lingui/blob/main/packages/loader/src/index.js#L60) which leads to a problem that all translation resources always resolved relatively to current package and makes impossible to import `.po` files from another shared packages

**Comment by SebasG22** [comment]
This [bug](#894 ) is related to this conversation, regarding some unclear errors to setup monorepos

**Comment by StupidIncarnate** [comment]
If I were to do documentation for it there's a couple caveats to consider:
- We do monorepo with babel-module-resolver https://github.com/lingui/js-lingui/issues/933, so not really current standard of lerna or yarn workspaces. Is that fine?
- I'd wanna ref an example repo since there's a lot of little config pieces. Would that just go here? https://github.com/lingui/js-lingui/tree/main/examples

The funny thing is I got it working in our monorepo but then because I needed restrictions in our pipeline around the extract to make sure people weren't skipping the pre-commit hooks, I didn't need it config'd from a monorepo perspective.

So do you want it documented from a monorepo perspective or from a "you can have localizations in a shared component lib, here's how to do it" setup which is in a monorepo but you don't run lingui from root because of the path issue?

**Comment by adam-thomas-privitar** [comment]
One issue with lingui's monorepo support is that practically, theres no way of having the extraction be aware of every package. Since lingui affectively runs per package.

This is a problem since if you have some core translations you want shared in a `core` module, and these are used across many other modules, they'll end up being extracted to each package they are consumed in, rather than being put into the `core` one. This is mainly because it lacks namespacing.

The documentation could outlined this issue.

**Comment by semoal** [comment]
> One issue with lingui's monorepo support is that practically, theres no way of having the extraction be aware of every package. Since lingui affectively runs per package.
> 
> This is a problem since if you have some core translations you want shared in a `core` module, and these are used across many other modules, they'll end up being extracted to each package they are consumed in, rather than being put into the `core` one. This is mainly because it lacks namespacing.
> 
> The documentation could outlined this issue.

I have to find time to analyze one option that was introduced by Tomas on v3 that is `catalogsMergePath`, I'm not sure if it's working properly but was introduced to fix the case you described.

We can have multiple modules but at the end of extracting wrap them in a single space, this will allow having @module/i18n in our monorepo where every package inside that monorepo could load any translation.

There's pending of work in terms of documentation and code, but we're open to contributions =)

**Comment by mgrosperrin** [comment]
Hi @StupidIncarnate 
> So do you want it documented from a monorepo perspective or from a "you can have localizations in a shared component lib, here's how to do it" setup which is in a monorepo but you don't run lingui from root because of the path issue?

Regarding this comment, it seems you have been able to add translations to a shared component lib. We are trying to do that too but haven't found any documentation or information on how to do it (except in monorepo which is not our case).
Have you been able to do it outside of a monorepo, and if yes, can we chat about it?
Thanks

**Comment by cezarneaga** [comment]
Dont have a solution, no.

**Comment by StupidIncarnate** [comment]
> Hi @StupidIncarnate
> 
> > So do you want it documented from a monorepo perspective or from a "you can have localizations in a shared component lib, here's how to do it" setup which is in a monorepo but you don't run lingui from root because of the path issue?
> 
> Regarding this comment, it seems you have been able to add translations to a shared component lib. We are trying to do that too but haven't found any documentation or information on how to do it (except in monorepo which is not our case). Have you been able to do it outside of a monorepo, and if yes, can we chat about it? Thanks

I don't see how you'd do that if not in a monorepo setup. It needs to know your folder ecosystem from what I remember and map from a root folder. I guess you could try the whole git sub repos but no clear idea how you'd do that.
