### ISSUE TITLE
[Long-term feature] - Migrate from rst to markdown

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#837]
**Is your feature request related to a problem? Please describe.**
I think having the documentation with Python and Re-StructuredText adds complexity to new contributors to add changes.
- It's so complex to launch to js users (normally they don't have pip installed)
- It's complex to preview
- Have some design limitations

**Describe proposed solution**
- Migrate to mdx https://mdxjs.com/
- Add docusaurus https://v2.docusaurus.io/

**Additional context**
For me this is a long term feature, that we'll should work without pressure, and a cool opportunity to improve documentation structure and his content to match all the great features that Lingui has.

**Comment by tricoder42** [comment]
I'm having an opposite opinion and it haven't changed over the years.

The first version of documentation was actually written in Markdown and published as a repository wiki. I consider reStructuredText superior to Markdown, because it's syntax allow user extensions. Markdown doesn't allow that — the only way to add new features is invent a new syntax (e.g. `remark` does that). It means that for reStructuredText there's just one parser (sadly python only) which can be extended. For Markdown, there're many parsers, each of them has sligtly different features.

For me the biggest selling point of reStructuredText are cross references. E.g. I can create a custom reference `:jsxmacro:'Trans'` and it'll point to the right location no matter where the current documentation for `Trans` macro lives. Not only it creates a correct link, it also validates that I'm referencing existng entity. This work for objects, sections, documents, everything. Not sure if there's something new in markdown world, but typing `[entity](url-to-the-entity)` all the time was very tedious as the project start growing.

I've discussed it with my friend a year ago — he also maintains JS project and migrated it's documentation from reStructuredText to Markdown for very same reason: easier for outside contributors. Unfortunately, in reality it's him writing the most of documentation and there's very little input from outside contributors. So, he basically traded a solid markup language which is easy to maintain for a popular language, which is harder to maintain and still it's mostly him who's working with it.

---

Now, to your points:

> It's so complex to launch to js users (normally they don't have pip installed)

You don't need to install anything locally. GitHub has a pretty decent preview of reStructuredText (e.g. rendered [migration docs](https://github.com/lingui/js-lingui/blob/main/docs/releases/migration-1.rst)). Also, you can just edit the `rst` file and send a PR. It most cases it's alright. It usually requires very few or none changes from my side.

> It's complex to preview

Not sure what do you mean. It's one markup language vs another markup language. They both are designed to be readable in their source form without need for rendering. I found reStructuredText as (un)redable as Markdown.

> Have some design limitations

What limitations? As I mentioned, user extensions are baked in reStructuredText syntax which is very similar to React components:

```
.. my-own-extension: Hello World
   :prop: 42
   :isVisible: true

   Here comes the content
```

---

On the other hand I understand that the tooling and community around Markdown is growing. It's easier to integrate md docs into Next.js/Gatsby website (I still have a poc of using reStructuredText inside Gatsby inside one of my branches, but it still requires a python env). It's easier to integrate React into documentation and make it interactive. I've been watching closely all these cool tools which pop up over the years, but none of them convinced me completely.

I really like the community and direction where Markdown is going. I just feel the Markdown itself is an unfortunate starting point for all these tools.  At the same time I really like the reStructuredText but I'm puzzled why there isn't much development around this language. I've tried to write my own parser of reStructuredText in Javascript a year ago, but haven't enough time to finish it: https://github.com/rst-js/rst-js (the `feature/parser` branch actually contains the parser. I endup writing parser fo r directives)

---

That said, if you'd like to migrate the whole documentation to Markdown and then continue maintain it, feel free to do so. I've never felt that the tool itself is a problem, rather the content which could be improved in many ways.

**Comment by semoal** [comment]
Interesting point of view Tom, was just a proposal but If you feel more conformable with rst, i'll go with rst (it's not that bad, in my case was just unfamiliar with it)

**Comment by tricoder42** [comment]
I honestly don't consider neither approach ideal (Markdown with superb integration vs superb reStructuredText with lack of integration). I just wanted to give you the full background story.

I would love to have indexed search (as Tailwindcss does). Interactive components would be great to understand how macros and message format works. New design would be great too. Not sure if it's worth it to migrate the whole docs

**Comment by semoal** [comment]
> I would love to have indexed search (as Tailwindcss does). Interactive components would be great to understand how macros and message format works. New design would be great too. Not sure if it's worth it to migrate the whole docs

Yes, that was just we need with the current documentation. I'm super noob with rst eco-system, that's why I suggested markdown because there are amazing tools around it that could help us getting all that features.

To be honest I get hot thinking in a documentation like Tailwinds for Lingui haha
