### ISSUE TITLE
Support `msgctx`

### ISSUE THREAD

**Issue by tricoder42** [lingui/js-lingui#856]
- [ ] Add `context` prop to message descriptor (used in `defineMessage` and `t` macros)
- [ ] Add `context` prop to `Trans` macro and also `Trans` component (from `@lingui/macro`)
- [ ] Collect `context` in extract plugin. In `cli` package, throw an error when file format is anything else than `po`
- [ ] Refactor `@lingui/core` to support lookup by context. Right now you get a translation using a simple object lookup `catalog[messageId] === translation`
- [ ] Add documentation

Related discussion: https://github.com/lingui/js-lingui/issues/845#issuecomment-725728398
Related issues: #598 #797 #298

**Comment by nakkamarra** [comment]
@tricoder42 Awesome, let me know if you'd like some help, I can maybe spend some time this weekend to make a PR.

**Comment by semoal** [comment]
Feel free to take it a provide a pull request Nick, I assign this to you, if you dont mind

**Comment by tricoder42** [comment]
@nakkamarra Definitely go ahead. I've created the issue only to outline what's required to do

**Comment by Bertg** [comment]
I'll probably have some time to work on this tomorrow (Wed 17th Central European timezone).
Is someone wants to pair up, let me know.

**Comment by nakkamarra** [comment]
@Bertg Yeah that sounds good. I've gotten started on this and am happy to chat about where I've gotten. However, I think there are some implications for the changes, particularly around how we will handle `missing` when message context is part of the equation, that I have not yet figured out.

**Comment by Bertg** [comment]
I worked a bit on this tonight and wanted to collect some feedback before finalising and creating a PR. (Especially @tricoder42)

https://github.com/lingui/js-lingui/compare/main...Bertg:msgctxt_support

What works: 

- Extract messages and remain uniq based on context
- Lookup based on context

When extracting messages & during lookup at runtime an Object (hash) is used. Before these changes the key was the ID. A simple approach would have been to change the key to an array of strings, however this leads to several issues. The extract process wants to serialise its internal structure to JSON which does not support arrays as keys, and I assume lookup of object with arrays as keys is not that performant. So I chose to replace the ID as key with a this: `[id, context].reject(s => !s).join('\u001F')`. This yield the same key for existing transactions and creates a uniq key for messages with a context. 

I chose `\u001F` as the separator character, as it is a control character and thus very unlikely to be in an ID or context string. A downside of this is that it is not "visible" when a developer wants to debug the output. We could choose an other rare, but visible character and maybe make it configurable? Or should we take a completely different approach?

A separater character is required so that these 2 translations would be unique: `t({id: "hihello"})` and `t({id: "hi", context: "hello"})`. Using a simple separator character is can yield problems. Imagine we use `-` as the separator, then these 2 would be identical: `t({id: "hi-hello"})` and `t({id: "hi", context: "hello"})`.

What still needs to be done:

- alphabetical sorting should take context into account
- errors when not using PO files (although, i think it could work with a visual separator character)
- macros

Opportunities:

With the key no longer being the ID itself, we could shorten the lookup keys, and reduce the payload size of translations. 
A hash could be made of the ID + context and used for lookup. We should weigh off the benefits of a smaller payload with the negative performance impact the hashing would have at runtime. Do note that with macros this performance impact woud not be felt at runtime, and could be a huge perforce improvements on bigger projects.

**Comment by tricoder42** [comment]
> With the key no longer being the ID itself, we could shorten the lookup keys, and reduce the payload size of translations.
A hash could be made of the ID + context and used for lookup. We should weigh off the benefits of a smaller payload with the negative performance impact the hashing would have at runtime. Do note that with macros this performance impact woud not be felt at runtime, and could be a huge perforce improvements on bigger projects.

This is good idea. I wanted to do sth similar while ago, see https://github.com/lingui/js-lingui/issues/139#issuecomment-411504660. However, I would do it in a separate issue/PR, because that could be implemented for all message formats, not only `po` files. Feel free to open a new one to start a discussion.

> I chose \u001F as the separator character, as it is a control character and thus very unlikely to be in an ID or context string. A downside of this is that it is not "visible" when a developer wants to debug the output. We could choose an other rare, but visible character and maybe make it configurable? Or should we take a completely different approach?

I think this is a good approach. If developer will debug the output, they'll see sth like `ctxmsgId` right? The separator is invisible, and they'll simply see two strings joined together. I think this is enough for debugging

All in all it looks good! Thanks for tackling this 👍

**Comment by Bertg** [comment]
Cool. With @tricoder42 and @nakkamarra blessings in my pocket, I'll see if I can wrap this up over the weekend.

**Comment by Bertg** [comment]
Hi! Sorry I've been quite busy. I'll make some time this weekend to wrap this up.

**Comment by nakkamarra** [comment]
Hey @semoal I've got some time to work on this, I'm going to take a look today + tomorrow, if you'd like to reopen it.
