### ISSUE TITLE
Locale data for locale "xx" not loaded. Plurals won't work correctly.

### ISSUE THREAD

**Issue by goozo** [lingui/js-lingui#977]
**Describe the bug**
It seems (or at least I could not find) documentation regarding a couple of things for React Setup. 

I was having issues in browser and in tests where I'd see the warning "Locale data for locale "xx" not loaded. Plurals won't work correctly."

**To Reproduce**
follow the current example on https://lingui.js.org/tutorials/react.html

**Expected behavior**
addition to the docs explaining `i18n.loadLocaleData`  and `make-plural` dependency in the setup docs/examples.

https://lingui.js.org/tutorials/setup-cra.html  - add info about (`make-plural` dependency)
https://lingui.js.org/tutorials/react.html - add to examples (`i18n.loadLocaleData('en', { plurals: en })`)
https://lingui.js.org/ref/core.html - add info about (`i18n.loadLocaleData`)

**Additional context**
It seems a lot of examples use "make-plural/plurals"  but this dependency is not explained (for noobs like me) or used in the React Setup Examples. `i18n.loadLocaleData`  is not really explained in the Docs, I'm not really sure what it does and how it differs from `i18n.load`. 

Once I installed the `make-plural` dependency and added the following the warning went away:
```
import { en } from 'make-plural/plurals';

i18n.loadLocaleData('en', { plurals: en });

```

- jsLingui version `3.5.1`
- Babel version `7.12.16`
- Babel config (Create React App)

**Comment by semoal** [comment]
Lingui uses plurals defined in `make-plural` which parses CLDR plural rules. Is it required to Lingui to know what plurals are referenced to each locale. 
We'll create a section explaining this more deeply, it's a really lightweight lib with treeshaking so you don't have to worry too much about bundle size.

**Comment by tommie-lie** [comment]
While refactoring our own code, I also stumbled upon every `load()` being accompanied by a `loadLocaleData`. I noticed `make-plural` is a dependency of lingui anyway and there even is some (apparently?) dead code that uses it: https://github.com/lingui/js-lingui/blob/main/packages/core/src/dev/loadLocaleData.ts

I am always a big fan of computers doing stuff for me, so when lingui can even tell me what to do, namely "load plurals for locale XX", why can't it do it on its own? How about, instead of printing the above warning in https://github.com/lingui/js-lingui/blob/main/packages/core/src/i18n.ts#L149 we just load the plural data? Are there any drawbacks or reasons why this was removed (according to git history, the `loadLocaleData.ts` file was still used in lingui 2.0)? If not, I volunteer to work on this.
